In [1]:
!pip install selenium

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: selenium in c:\users\gouri patnaik\appdata\roaming\python\python39\site-packages (4.11.2)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\gouri patnaik\appdata\roaming\python\python39\site-packages (from selenium) (0.10.3)
Requirement already satisfied: certifi>=2021.10.8 in c:\programdata\anaconda3\lib\site-packages (from selenium) (2022.9.14)
Requirement already satisfied: urllib3[socks]<3,>=1.26 in c:\programdata\anaconda3\lib\site-packages (from selenium) (1.26.11)
Requirement already satisfied: trio~=0.17 in c:\users\gouri patnaik\appdata\roaming\python\python39\site-packages (from selenium) (0.22.2)
Requirement already satisfied: attrs>=20.1.0 in c:\programdata\anaconda3\lib\site-packages (from trio~=0.17->selenium) (21.4.0)
Requirement already satisfied: sniffio in c:\programdata\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: outcome in c:\users\gouri patnaik\appdata\roaming\python\python39\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: cffi>=1.14 in c:\programdata\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.15.1)
Requirement already satisfied: sortedcontainers in c:\programdata\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: idna in c:\programdata\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.3)
Requirement already satisfied: exceptiongroup>=1.0.0rc9 in c:\users\gouri patnaik\appdata\roaming\python\python39\site-packages (from trio~=0.17->selenium) (1.1.2)
Requirement already satisfied: wsproto>=0.14 in c:\users\gouri patnaik\appdata\roaming\python\python39\site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in c:\programdata\anaconda3\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: pycparser in c:\programdata\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\gouri patnaik\appdata\roaming\python\python39\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)

In [1]:
#imports

import selenium
import pandas as pd
import time
from bs4 import BeautifulSoup

#importing selenium webdriver

from selenium import webdriver

#importing required exceptions which need to be handled
from selenium.common.exceptions import StaleElementReferenceException,NoSuchElementException

#importing requests
import requests
from selenium.webdriver.common.by import By
import re

## 1. www.nike.com

In [198]:
driver=webdriver.Chrome()

In [199]:
driver.get('https://www.nike.com/')

In [200]:
search_item=driver.find_element(By.XPATH,'/html/body/div[3]/div/div[3]/header/div[1]/div[2]/div/div/div[1]/div/div/input')
search_item.send_keys('shoes')
search_item.click()
time.sleep(5)

In [201]:
shoes=driver.find_element(By.XPATH,'/html/body/div[3]/div/div[3]/header/div[1]/div[2]/div/div/div[2]/div[2]/div[1]/ul/li[1]/a/span')
shoes.click()

In [202]:
# Table.1.1:
shoe_name=[]
category=[]
no_of_colors=[]
price=[]

In [203]:
for _ in range(0,1):
    driver.execute_script("window.scrollBy(0,10)")
             
    # to scrap shoe_name
    try:
        name_tag=driver.find_elements(By.XPATH,'//div[@class="product-card__title"][1]')
        for i in name_tag:
            shoe_name.append(i.text)   
            
    except NoSuchElementException:
         shoe_name.append('-')       
    
    # to scrap category:
    try:
        category_tag=driver.find_elements(By.XPATH,'//div[@class="product-card__subtitle"][1]')
        for i in category_tag:
            
            result=re.search(r"\bWomen\b|\bMen\b|\bkid's\b|\bchild\b",str(i.text))
            if result is None:
                category.append(None)
                
            else:    
                category.append(result.group(0))
            
            #category.append(i.text)
            
        
    except NoSuchElementException:
         category.append('-')       
    
    # to scrap no_of_colors:
    
    try:
        colors_tag=driver.find_elements(By.XPATH,'//div[@class="product-card__count-item"][1]')
        for i in colors_tag:
            no_of_colors.append(i.text) 
            
    except NoSuchElementException:
         no_of_colors.append('-')   
            
    # to scrap price
    try:
        price_tag=driver.find_elements(By.XPATH,'//div[@class="product-card__price"][1]')
        for i in price_tag:
            price.append(i.text)
            
    except NoSuchElementException:
         price.append('-') 
            
     #to scrap url:
    shoe_url=[]
    try:
        url_tag=driver.find_elements(By.XPATH,'//*[@data-testid="product-card__link-overlay"]')
        for i in url_tag:
            shoe_url.append(i.get_attribute("href"))
            
    except NoSuchElementException:
         shoe_url.append('-')           
            
                
print(len(shoe_name),len(category),len(no_of_colors),len(price),len(shoe_url))

24 24 24 24 24

In [204]:
table1={"SHOE_NAME":shoe_name,"CATEGORY":category,"NO_OF_COLORS":no_of_colors,"PRICE":price}
df1=pd.DataFrame(table1)
df1

                            SHOE_NAME CATEGORY NO_OF_COLORS              PRICE
0             Nike Killshot 2 Leather      Men    5 Colours   MRP : ₹ 7 995.00
1                     Nike Air Max SC    Women    4 Colours   MRP : ₹ 5 995.00
2            Nike Air Force 1 '07 LV8      Men     1 Colour  MRP : ₹ 10 795.00
3               Nike Court Vision Low     None     1 Colour   MRP : ₹ 4 995.00
4             Nike Air Force 1 '07 NN    Women    2 Colours   MRP : ₹ 9 695.00
5              Nike Court Legacy Lift    Women    5 Colours   MRP : ₹ 7 495.00
6             Nike Air Force 1 Shadow    Women     1 Colour   MRP : ₹ 9 295.00
7              NikeCourt Legacy Suede      Men     1 Colour   MRP : ₹ 5 995.00
8                  Nike Air Max Pulse    Women    5 Colours  MRP : ₹ 13 995.00
9   Nike Court Vision Low Next Nature    Women    5 Colours   MRP : ₹ 4 995.00
10                        Nike Cortez    Women    4 Colours   MRP : ₹ 7 495.00
11               Nike Air Force 1 '07      Men    2 Colours  MRP : ₹ 11 895.00
12           Nike Blazer Low Platform    Women    4 Colours   MRP : ₹ 8 195.00
13                Nike Phoenix Waffle    Women    4 Colours   MRP : ₹ 8 695.00
14                   Nike SB Force 58     None    3 Colours   MRP : ₹ 6 295.00
15       NikeCourt Legacy Next Nature    Women    3 Colours   MRP : ₹ 5 695.00
16     Nike SB Zoom Blazer Low Pro GT     None    4 Colours   MRP : ₹ 6 795.00
17          Air Jordan Legacy 312 Low      Men    4 Colours  MRP : ₹ 12 995.00
18                  Nike Waffle Debut      Men    2 Colours   MRP : ₹ 7 095.00
19                        Nike P-6000     None     1 Colour   MRP : ₹ 7 995.00
20                     Nike Tech Hera    Women    6 Colours   MRP : ₹ 9 695.00
21             Nike Court Vision Alta    Women    4 Colours   MRP : ₹ 5 995.00
22                  Nike Waffle Debut    Women    5 Colours   MRP : ₹ 5 695.00
23              Nike Air Force 1 Wild    Women    6 Colours  MRP : ₹ 12 795.00

# Table:2

In [205]:
shoe_url

['https://www.nike.com/in/t/killshot-2-leather-shoe-DqWZ4j/432997-111',
 'https://www.nike.com/in/t/air-max-sc-shoes-FVn5sK/CW4554-117',
 'https://www.nike.com/in/t/air-force-1-07-lv8-shoes-lPdFPQ/FJ4170-002',
 'https://www.nike.com/in/t/court-vision-low-shoes-bv8p57/CD5463-102',
 'https://www.nike.com/in/t/air-force-1-07-nn-shoes-nCJ6Wb/DV3808-001',
 'https://www.nike.com/in/t/court-legacy-lift-shoes-1zLxsK/DM7590-105',
 'https://www.nike.com/in/t/air-force-1-shadow-shoes-hzR7HR/DO7449-111',
 'https://www.nike.com/in/t/nikecourt-legacy-suede-shoes-QcMfd3/DH0956-002',
 'https://www.nike.com/in/t/air-max-pulse-shoes-V9B1C5/FD6409-202',
 'https://www.nike.com/in/t/court-vision-low-next-nature-shoes-p3CnbT/DH3158-109',
 'https://www.nike.com/in/t/cortez-shoes-svdKM9/DN1791-105',
 'https://www.nike.com/in/t/air-force-1-07-shoes-587rld/FZ4627-400',
 'https://www.nike.com/in/t/blazer-low-platform-shoes-1g6h57/DJ0292-113',
 'https://www.nike.com/in/t/phoenix-waffle-shoes-Px0WgL/FD2196-101',
 'https://www.nike.com/in/t/sb-force-58-skate-shoes-LJNW5L/DV5477-800',
 'https://www.nike.com/in/t/nikecourt-legacy-next-nature-shoes-rdTfqH/DH3161-108',
 'https://www.nike.com/in/t/sb-zoom-blazer-low-pro-gt-skate-shoes-ckWK6g/DC7695-403',
 'https://www.nike.com/in/t/air-jordan-legacy-312-low-shoes-6Vd4Xl/CD7069-110',
 'https://www.nike.com/in/t/waffle-debut-shoes-4j1X82/FJ4195-001',
 'https://www.nike.com/in/t/p-6000-shoe-QcQbpx/CD6404-101',
 'https://www.nike.com/in/t/tech-hera-shoes-JlV5km/DR9761-401',
 'https://www.nike.com/in/t/court-vision-alta-shoes-p7Dnlp/DM0113-005',
 'https://www.nike.com/in/t/waffle-debut-shoes-hbBJtw/DH9523-106',
 'https://www.nike.com/in/t/air-force-1-wild-shoes-FCjQ2C/FB2348-003']

In [206]:
# Table.2.
color1=[]
color2=[]
color3=[]
color4=[]
color5=[] 
Style_code=[]

In [207]:
# scraping table2 data
count_of_size=[]
for url in shoe_url:
    driver.get(url)
    time.sleep(5)
    
    
    # to scrap count_of_sizes:
    try:
        
        count_tag=driver.find_elements(By.XPATH,'//div[@class="prl6-sm prl0-lg"][1]')
        #Extracting the table data:
       
        count=0
        matches=driver.find_elements(By.TAG_NAME,'/fieldset/div/div')
        for match in matches:
            count=count+1
        count_of_size.append(count)
      
    except NoSuchElementException:
        count_of_size.append('-') 
           
    # to scrap color1:
    try:
        color1_tag=driver.find_element(By.XPATH,'//ul[@class="description-preview__features pt8-sm pb6-sm ncss-list-ul"]/li[1]')
        colors1=color1_tag.text.split('/')
        
        color1.append(colors1[0].split(':')[1])
            
    except NoSuchElementException:
        color1.append('-')         
            
            
     # to scrap color2:
    try:
        color2_tag=driver.find_element(By.XPATH,'//ul[@class="description-preview__features pt8-sm pb6-sm ncss-list-ul"]/li[1]')
        colors2=color2_tag.text.split('/')
        color2.append(colors2[1])
            
    except NoSuchElementException:
         color2.append('-')   
            
    #to scrap color3:
    try:
        color3_tag=driver.find_element(By.XPATH,'//ul[@class="description-preview__features pt8-sm pb6-sm ncss-list-ul"]/li[1]')
        colors3=color3_tag.text.split('/')
        if len(colors3)>=3:
            color3.append(colors3[2])
            
        else:
            color3.append('-')
        
    except NoSuchElementException:
        color3.append('-')  
            
    # to scrap color4:
    try:
        color4_tag=driver.find_element(By.XPATH,'//ul[@class="description-preview__features pt8-sm pb6-sm ncss-list-ul"]/li[1]')
        colors4=color4_tag.text.split('/')
        if len(colors4)>=4:
            color4.append(colors4[3])
        else:
            color4.append('-')
    except NoSuchElementException:
        color4.append('-')    
            
     # to scrap color5:
    try:
        color5_tag=driver.find_element(By.XPATH,'//ul[@class="description-preview__features pt8-sm pb6-sm ncss-list-ul"]/li[1]')
        colors5=color5_tag.text.split('/')
        if len(colors5)>=5:
            color5.append(colors5[4])
        else:
            color5.append('-')
    except NoSuchElementException:
        color5.append('-')     
            
     # to scrap style_code:
    try:
        style_tag=driver.find_element(By.XPATH,'//ul[@class="description-preview__features pt8-sm pb6-sm ncss-list-ul"]/li[2]')
        Style_code.append(style_tag.text)
            
    except NoSuchElementException:
        Style_code.append('-')  
        
    
print(len(count_of_size),len(color1),len(color2),len(color3),len(color4),len(color5),len(Style_code))

24 24 24 24 24 24 24

In [208]:
colors1

['Colour Shown: Platinum Violet', 'Smokey Mauve', 'Earth', 'Platinum Violet']

In [209]:
colors1[1]

'Smokey Mauve'

In [210]:
colors1[2]

'Earth'

In [211]:
colors3[2]

'Earth'

In [212]:
table2_1={"COUNT_OF_SIZES":count_of_size,"COLOR1":color1,"COLOR2":color2,"COLOR3":color3,"COLOR4":color4,"COLOR5":color5,"STYLE_CODE":Style_code}
df21=pd.DataFrame(table2_1)
df21

,COUNT_OF_SIZES,COLOR1,COLOR2,COLOR3,COLOR4,COLOR5,STYLE_CODE
0,0,Sail,Gum Yellow,Lucid Green,-,-,Style: 432997-111
1,0,White,Sea Glass,Black,Chlorophyll,-,Style: CW4554-117
2,0,Dark Stucco,Neutral Olive,Phantom,Medium Olive,-,Style: FJ4170-002
3,0,White,University Red,-,-,-,Style: CD5463-102
4,0,Platinum Violet,Coconut Milk,Volt,Sail,-,Style: DV3808-001
5,0,White,Smokey Mauve,Platinum Violet,-,-,Style: DM7590-105
6,0,Sail,Sail,Grey Fog,Pale Ivory,-,Style: DO7449-111
7,0,Cobblestone,Black,Gum Light Brown,White,-,Style: DH0956-002
8,0,Light Violet Ore,Platinum Violet,Sail,Smokey Mauve,-,Style: FD6409-202
9,0,White,Platinum Violet,-,-,-,Style: DH3158-109
10,0,White,Smokey Mauve,Black,Platinum Violet,-,Style: DN1791-105
11,0,Light Armoury Blue,White,-,-,-,Style: FZ4627-400
12,0,Pale Ivory,White,Saturn Gold,-,-,Style: DJ0292-113
13,0,Light Orewood Brown,Team Gold,Light Iron Ore,Midnight Navy,-,Style: FD2196-101
14,0,Monarch,Midnight Navy,Gum Light Brown,Persian Violet,-,Style: DV5477-800
15,0,White,Wheat,Ashen Slate,-,-,Style: DH3161-108
16,0,Court Blue,Court Blue,University Red,Light Orewood Brown,-,Style: DC7695-403
17,0,White,Black,Sail,Wolf Grey,-,Style: CD7069-110
18,0,Black,Off-Noir,White,-,-,Style: FJ4195-001
19,0,Sail,Wolf Grey,Metallic Silver,White,-,Style: CD6404-101
20,0,Ashen Slate,Platinum Violet,Anthracite,Football Grey,-,Style: DR9761-401
21,0,Platinum Violet,White,-,-,-,Style: DM0113-005
22,0,Summit White,Smokey Mauve,Platinum Violet,Summit White,-,Style: DH9523-106
23,0,Platinum Violet,Smokey Mauve,Earth,Platinum Violet,-,Style: FB2348-003

# Table.3:

In [213]:
# Table.3 :
reviews=[]
star_rating=[]
size=[]
comfort=[]
quality=[]

In [214]:
for url in shoe_url:
    driver.get(url)
    time.sleep(5)
    
    # to scrap no of reviews   
    try:
        
        no_of_reviews=driver.find_element(By.XPATH,'//summary[@class=" css-rptnlm"]/h3/span[1]')
        reviews.append(no_of_reviews.text)
                                          
    except NoSuchElementException:
         reviews.append('-')  
        
     # to scrap star_rating:
    try:
        reviews_tag=driver.find_element(By.XPATH,'//h3[@class="headline-4"]/span')
        reviews_tag.click
        rating_tag=driver.find_element(By.XPATH,'//p[@class="d-sm-ib pl4-sm"]')
        res=rating_tag.text.split(" ")
        if len(res)>=1:
            star_rating.append(res[0])
        else:
            star_rating.append('-')
    except NoSuchElementException:
        star_rating.append('-') 
        
        
    try:
        
        size_tag=driver.find_element(By.XPATH,'//summary[@class=" css-rptnlm"]/h3/span[1]')
        size.append('-')
        
    except NoSuchElementException:
         size.append('-')  
            
    try:
        
        comfort_tag=driver.find_element(By.XPATH,'//summary[@class=" css-rptnlm"]/h3/span[1]')
        comfort.append('-')
        
    except NoSuchElementException:
        comfort3.append('-')  
        
    try:
       
        quality_tag=driver.find_element(By.XPATH,'//summary[@class=" css-rptnlm"]/h3/span[1]')
        quality.append('-')
        
    except NoSuchElementException:
        quality.append('-')     
        
        
print(len(reviews),len(star_rating),len(size),len(comfort),len(quality))

24 24 24 24 24

In [215]:
table3_1={"REVIEWS":reviews,"STAR_RATING":star_rating,"SIZE":size,"COMFORT":comfort,"QUALITY":quality}
df31=pd.DataFrame(table3_1)
df31

          REVIEWS STAR_RATING SIZE COMFORT QUALITY
0    Reviews (72)                -       -       -
1   Reviews (129)                -       -       -
2     Reviews (0)                -       -       -
3   Reviews (186)                -       -       -
4    Reviews (12)                -       -       -
5    Reviews (73)                -       -       -
6     Reviews (0)                -       -       -
7     Reviews (3)                -       -       -
8    Reviews (32)                -       -       -
9    Reviews (50)                -       -       -
10   Reviews (39)                -       -       -
11    Reviews (0)                -       -       -
12  Reviews (174)                -       -       -
13   Reviews (33)                -       -       -
14   Reviews (21)                -       -       -
15  Reviews (109)                -       -       -
16   Reviews (19)                -       -       -
17   Reviews (36)                -       -       -
18    Reviews (0)                -       -       -
19   Reviews (20)                -       -       -
20   Reviews (71)                -       -       -
21   Reviews (66)                -       -       -
22   Reviews (78)                -       -       -
23   Reviews (24)                -       -       -

# 2. adidas.co.in

In [216]:
driver=webdriver.Chrome()

In [217]:
driver.get('https://www.adidas.com')

In [218]:
search_item=driver.find_element(By.XPATH,'/html/body/div[1]/div[2]/div[2]/div/header/div[2]/div/div[2]/div/input')
search_item.send_keys('shoes')
search_item.click()
time.sleep(5)

In [219]:
shoes=driver.find_element(By.XPATH,'/html/body/div[1]/div[2]/div[2]/div/header/div[2]/div/div[2]/div/div[2]/div/div[1]/div[2]/a[5]/div[1]')
shoes.click()

In [220]:
# Table.1.2:
shoe_name2=[]
category2=[]
no_of_colors2=[]
price2=[]

In [221]:
for page in range(0,1):
    
    
    
    # to scrap shoe_name
    try:
        name_tag=driver.find_elements(By.XPATH,'//div[@class="glass-product-card__details"]/p[1]')
        for i in name_tag:
            shoe_name2.append(i.text)
            
    except NoSuchElementException:
         shoe_name2.append('-')  
        
    
    # to scrap category:
    try:
        category_tag=driver.find_elements(By.XPATH,'//div[@class="glass-product-card__details"]/p[2]')
        for i in category_tag:
            result=re.search(r"\bWomen\b|\bMen\b|\boriginals\b|\bchild\b",str(i.text))
            if result is None:
                category2.append(None)
                
            else:    
                category2.append(result.group(0))
            
            #category2.append(i.text)
    except NoSuchElementException:
         category2.append('-')         
    
    # to scrap no_of_colors:
    try:
        colors_tag=driver.find_elements(By.XPATH,'//div[@class="glass-product-card__details"]/p[3]')
        for i in colors_tag:
            no_of_colors2.append(i.text)   
            
    except NoSuchElementException:
         no_of_colors2.append('-')         
       
    # to scrap price
    try:
        price_tag=driver.find_elements(By.XPATH,'//a[@class="product-card-content-badges-wrapper___2RWqS"][1]')
        for i in price_tag:
            price2.append(i.text)
            
    except NoSuchElementException:
         price2.append('-')         
            
    
   
    next_button=driver.find_element(By.XPATH,'/html/body/div[2]/div/div[1]/div[1]/div/div/div[5]/div/div[3]/div/div/div/div[2]/div/div/div/div[4]/a/span')
    next_button.click()                                 
    time.sleep(5)    
        
print(len(shoe_name2),len(category2),len(no_of_colors2),len(price2))

48 48 48 48

In [222]:
table1_2={"SHOE_NAME":shoe_name2,"CATEGORY":category2,"NO_OF_COLORS":no_of_colors2,"PRICE":price2}
df2=pd.DataFrame(table1_2)
df2

,SHOE_NAME,CATEGORY,NO_OF_COLORS,PRICE
0,Superstar Shoes,originals,3 colours,₹8 999.00
1,Samba OG Shoes,originals,2 colours,₹10 999.00
2,Samba OG Shoes,originals,2 colours,₹11 999.00
3,Superstar Shoes,Men,3 colours,₹8 999.00
4,Gazelle Shoes,originals,6 colours,₹10 999.00
5,VS Pace 2.0 Shoes,Men,7 colours,-30 %\n₹4 999.00\n₹3 499.50
6,Galaxy 6 Shoes,Men,9 colours · long distance run,₹5 999.00
7,Ultraboost Light,Men,3 colours,-40 %\n₹19 999.00\n₹11 999.50
8,Ultimashow Shoes,Men,6 colours,
9,Alphaboost V1 Shoes,Men,7 colours,
10,FLUIDFLOW 2.0 RUNNING SHOE,Men,,
11,Ultraboost 1.0 Shoes,Men,,
12,HYPERON 1.0 SHOES,Men,2 colours,
13,Grand Court Cloudfoam Comfort Shoes,Men,5 colours,
14,Pureboost 22 Shoes,None,3 colours,
15,Ultraboost 1.0 Shoes,Men,5 colours,
16,Adilette Slides,Men,2 colours,
17,Lite Racer Adapt 4.0 Cloudfoam Slip-On Shoes,Men,6 colours,
18,FLODEAN SHOES,Men,3 colours,
19,ACME SHOES,Men,3 colours,
20,Adilette Comfort Slides,None,3 colours,
21,Ozelle Cloudfoam Shoes,Men,9 colours,
22,Adilette Comfort Slides,None,,
23,SHEENWALK SHOES,Women,3 colours,
24,AMPLIGY SHOES,Men,3 colours,
25,NMD_R1 Shoes,Men,4 colours,
26,Ultimashow Shoes,Women,5 colours,
27,SHEENWALK SHOES,Women,3 colours,
28,RUNNING UNIFLOW SHOES,Men,,
29,Ultimashow Shoes,Men,6 colours,
30,Duramo 10 Shoes,Men,7 colours,
31,Asweetrain Shoes,Men,,
32,Galaxy 6 Shoes,Women,11 colours,
33,Ultra 4DFWD Shoes,None,,
34,SPORT INSPIRED THROB SHOES,Men,,
35,VS Pace 2.0 Shoes,Men,8 colours,
36,Advantage Base Court Lifestyle Shoes,Men,3 colours,
37,Gazelle Shoes,originals,,
38,Ultimashow Shoes,Men,6 colours,
39,Web BOOST Shoes,None,2 colours,
40,NMD_R1 Shoes,Men,4 colours,
41,NMD_R1 Shoes,originals,3 colours,
42,Stan Smith Shoes,originals,5 colours,
43,UBounce DNA Shoes,Men,4 colours,
44,Y-3 Gendo Pro Model,None,2 colours,
45,Y-3 Gendo Pro Model,None,2 colours,
46,Ultraboost 1.0 Shoes,Men,5 colours,
47,Superstar XLG Shoes,originals,5 colours,

## Table.2:

In [223]:
# Table.2.2:
count_of_size2=[]
color1_2=[]
color2_2=[]
color3_2=[]
color4_2=[]
color5_2=[] 
style_code_2=[]

In [225]:
for page in range(0,3):
   
    try:
        shoe_url2=[]
        url_tag=driver.find_elements(By.XPATH,'//div[@class="glass-product-card color-variations__fixed-size plp-product-card___2Tf-5 product-card-content___3R3aL lift-image___3FzoX"]/a')
        for i in url_tag:
            shoe_url2.append(i.get_attribute("href"))
            
    except NoSuchElementException:
         shoe_url2.append('-')   
            
    next_button=driver.find_element(By.XPATH,'//a[@class="active gl-cta gl-cta--tertiary"]/span[1]')
    next_button.click()                                 
    time.sleep(1)    
                
            
print(len(shoe_url2))

48

In [226]:
shoe_url2

['https://www.adidas.co.in/superstar-shoes/EG4959.html',
 'https://www.adidas.co.in/samba-og-shoes/B75807.html',
 'https://www.adidas.co.in/samba-og-shoes/B75806.html',
 'https://www.adidas.co.in/superstar-shoes/EG4958.html',
 'https://www.adidas.co.in/gazelle-shoes/BB5478.html',
 'https://www.adidas.co.in/vs-pace-2.0-shoes/HP6007.html',
 'https://www.adidas.co.in/galaxy-6-shoes/GW3848.html',
 'https://www.adidas.co.in/ultraboost-light/HQ1402.html',
 'https://www.adidas.co.in/ultimashow-shoes/FX3632.html',
 'https://www.adidas.co.in/alphaboost-v1-shoes/HP2760.html',
 'https://www.adidas.co.in/fluidflow-2.0-running-shoe/EX2102.html',
 'https://www.adidas.co.in/ultraboost-1.0-shoes/HQ6441.html',
 'https://www.adidas.co.in/hyperon-1.0-shoes/CM4822.html',
 'https://www.adidas.co.in/grand-court-cloudfoam-comfort-shoes/GW9195.html',
 'https://www.adidas.co.in/pureboost-22-shoes/HP9014.html',
 'https://www.adidas.co.in/ultraboost-1.0-shoes/GY7479.html',
 'https://www.adidas.co.in/adilette-slides/HP6508.html',
 'https://www.adidas.co.in/lite-racer-adapt-4.0-cloudfoam-slip-on-shoes/HP2677.html',
 'https://www.adidas.co.in/flodean-shoes/GC0569.html',
 'https://www.adidas.co.in/acme-shoes/GC0669.html',
 'https://www.adidas.co.in/adilette-comfort-slides/GY1945.html',
 'https://www.adidas.co.in/ozelle-cloudfoam-shoes/H03506.html',
 'https://www.adidas.co.in/adilette-comfort-slides/GZ5892.html',
 'https://www.adidas.co.in/sheenwalk-shoes/GC0557.html',
 'https://www.adidas.co.in/ampligy-shoes/GA0910.html',
 'https://www.adidas.co.in/nmd_r1-shoes/GX9886.html',
 'https://www.adidas.co.in/ultimashow-shoes/FX3639.html',
 'https://www.adidas.co.in/sheenwalk-shoes/GC0555.html',
 'https://www.adidas.co.in/running-uniflow-shoes/EY2997.html',
 'https://www.adidas.co.in/ultimashow-shoes/FX3624.html',
 'https://www.adidas.co.in/duramo-10-shoes/HP2383.html',
 'https://www.adidas.co.in/asweetrain-shoes/FW1662.html',
 'https://www.adidas.co.in/galaxy-6-shoes/HP2407.html',
 'https://www.adidas.co.in/ultra-4dfwd-shoes/HP7598.html',
 'https://www.adidas.co.in/sport-inspired-throb-shoes/CM4882.html',
 'https://www.adidas.co.in/vs-pace-2.0-shoes/HP6012.html',
 'https://www.adidas.co.in/advantage-base-court-lifestyle-shoes/GW9283.html',
 'https://www.adidas.co.in/gazelle-shoes/IG1062.html',
 'https://www.adidas.co.in/ultimashow-shoes/FX3631.html',
 'https://www.adidas.co.in/web-boost-shoes/HR0085.html',
 'https://www.adidas.co.in/nmd_r1-shoes/GX9885.html',
 'https://www.adidas.co.in/nmd_r1-shoes/GZ9260.html',
 'https://www.adidas.co.in/stan-smith-shoes/FX5502.html',
 'https://www.adidas.co.in/ubounce-dna-shoes/IG6001.html',
 'https://www.adidas.co.in/y-3-gendo-pro-model/IG2934.html',
 'https://www.adidas.co.in/y-3-gendo-pro-model/IG2935.html',
 'https://www.adidas.co.in/ultraboost-1.0-shoes/ID5879.html',
 'https://www.adidas.co.in/superstar-xlg-shoes/IG9777.html']

In [33]:
# scraping table2 data

for url in shoe_url2:
    driver.get(url)
    time.sleep(5)
    
    
    # to scrap count_of_sizes:
    try:
        #count_tag=driver.find_elements(By.XPATH,'//div[@class="sidebar___29cCJ"]/div[1]')
        count_of_size2.append('-')
        #count=0
        #matches=driver.find_elements(By.TAG_NAME,'/button')
        #for match in matches:
            #count=count+1             ### FACING PROBLEM IN LOADING THE SIZES TABLE, HENCE APPENDING "-"
        
           
    except NoSuchElementException:
         count_of_size2.append('-') 
            
    # to scrap color1:
    try:
        color1_2_tag=driver.find_element(By.XPATH,'//div[@class="color-label___2hXaD"][1]')
        colors12=color1_2_tag.text.split('/')
        color1_2.append(colors12[0])
            
    except NoSuchElementException:
         color1_2.append('-')         
            
            
     # to scrap color2:
    try:
        color2_2_tag=driver.find_element(By.XPATH,'//div[@class="color-label___2hXaD"][1]')
        colors22=color2_2_tag.text.split('/')
        color2_2.append(colors22[1])
            
    except NoSuchElementException:
         color2_2.append('-')   
            
    # to scrap color3:
    try:
        color3_2_tag=driver.find_element(By.XPATH,'//div[@class="color-label___2hXaD"][1]')
        colors32=color3_2_tag.text.split('/')
        if len(colors32)>=3:
            color3_2.append(colors32[2])
        else:
            color3_2.append('-')
    except NoSuchElementException:
         color3_2.append('-')  
            
    # to scrap color4:
    try:
        color4_2_tag=driver.find_element(By.XPATH,'//div[@class="color-label___2hXaD"][1]')
        colors42=color4_2_tag.text.split('/')
        if len(colors42)>=4:
            color4_2.append(colors42[3])
        else:
            color4_2.append('-')
    except NoSuchElementException:
         color4_2.append('-')    
            
     # to scrap color5:
    try:
        color5_2_tag=driver.find_element(By.XPATH,'//div[@class="color-label___2hXaD"][1]')
        colors52=color5_2_tag.text.split('/')
        if len(colors52)>=5:
            color5_2.append(colors52[4])
        else:
            color5_2.append('-')
    except NoSuchElementException:
         color5_2.append('-')     
            
     # to scrap style code:
    try:
        details=driver.find_element(By.XPATH,'//*[@id="navigation-target-specifications"]/div/button/div')
        details.click()
        style_tag2=driver.find_element(By.XPATH,'//div[@class="bullets___3bsSs"]/ul[2]/li[4]')
        style_code_2.append(style_tag2.text)
            
    except NoSuchElementException:
         style_code_2.append('-')  
    
            
print(len(count_of_size2),len(color1_2),len(color2_2),len(color3_2),len(color4_2),len(color5_2),len(style_code_2))

48 48 48 48 48 48 48

In [34]:
table2_2={"COUNT_OF_SIZES":count_of_size2,"COLOR1":color1_2,"COLOR2":color2_2,"COLOR3":color3_2,"COLOR4":color4_2,"COLOR5":color5_2,"STYLE_CODE":style_code_2}
df22=pd.DataFrame(table2_2)
df22

,COUNT_OF_SIZES,COLOR1,COLOR2,COLOR3,COLOR4,COLOR5,STYLE_CODE
0,-,Core Black,Cloud White,Core Black,-,-,-
1,-,Core Black,Cloud White,Gum,-,-,-
2,-,Cloud White,Core Black,Clear Granite,-,-,-
3,-,Cloud White,Core Black,Cloud White,-,-,-
4,-,Collegiate Navy,White,Gold Metallic,-,-,Product code: BB5478
5,-,Grey Three,Core Black,Cloud White,-,-,-
6,-,Core Black,Cloud White,Core Black,-,-,Colour: Core Black / Cloud White / Core Black
7,-,-,-,-,-,-,Colour: Wonder Red F22 / Cloud White / Wonder ...
8,-,Core Black,Core Black,Cloud White,-,-,Product code: FX3632
9,-,Core Black,Grey Five,Carbon,-,-,Product code: HP2760
10,-,-,-,-,-,-,Product code: EX2102
11,-,-,-,-,-,-,-
12,-,-,-,-,-,-,-
13,-,-,-,-,-,-,-
14,-,Cloud White,Core Black,Cloud White,-,-,Product code: GW9195
15,-,Core Black,Better Scarlet S23,Cloud White,-,-,Colour: Core Black / Better Scarlet S23 / Clou...
16,-,Light Solid Grey,Light Solid Grey,Bold Gold,-,-,-
17,-,Legend Ink,Legend Ink,Shadow Navy S22,-,-,-
18,-,Core Black,Dove Grey S20,-,-,-,Product code: GC0569
19,-,Core Black,Coffee Met.,Cloud White,-,-,-
20,-,Core Black,Cloud White,Core Black,-,-,-
21,-,-,-,-,-,-,Product code: GZ5892
22,-,-,-,-,-,-,-
23,-,Core Black,Cloud White,Grey Six,-,-,-
24,-,Red,Royal Blue,Off White,-,-,Product code: GX9886
25,-,Power Pink,Power Pink,Cloud White,-,-,Product code: FX3639
26,-,Blue Dawn,Collegiate Navy,-,-,-,-
27,-,-,-,-,-,-,-
28,-,Core Black,Core Black,Cloud White,-,-,-
29,-,Victory Blue,Cloud White,Lucid Blue,-,-,Colour: Victory Blue / Cloud White / Lucid Blue
30,-,-,-,-,-,-,Product code: FW1662
31,-,Cloud White,Silver Metallic,Coral Fusion S23,-,-,Colour: Cloud White / Silver Metallic / Coral ...
32,-,-,-,-,-,-,Yarn in upper contains at least 50% Parley Oce...
33,-,-,-,-,-,-,-
34,-,Cloud White,Cloud White,Grey Two,-,-,Product code: FX3631
35,-,Cloud White,Cloud White,Cloud White,-,-,Product code: HP6012
36,-,Cloud White,Cloud White,Core Black,-,-,Product code: GW9283
37,-,-,-,-,-,-,-
38,-,-,-,-,-,-,-
39,-,Cloud White,Off White,Green,-,-,Product code: GX9885
40,-,Cloud White,Cloud White,Gum,-,-,Product code: GZ9260
41,-,Cloud White,Cloud White,Green,-,-,-
42,-,Core Black,Core Black,Cloud White,-,-,Colour: Core Black / Core Black / Cloud White
43,-,-,-,-,-,-,-
44,-,-,-,-,-,-,-
45,-,Cloud White,Core Black,Better Scarlet S23,-,-,Product code: ID5879
46,-,Core Black,Cloud White,Gold Metallic,-,-,-
47,-,Grey,Grey,Bright Royal,-,-,Product code: IF7315

## Table.3:

In [228]:
# Table.3.2 :
reviews2=[]
star_rating2=[]
size2=[]
comfort2=[]
quality2=[]

In [229]:
for url in shoe_url2:
    driver.get(url)
    time.sleep(5)
    
            
     # to scrap reviews:
    try:
        review_tag=driver.find_element(By.XPATH,'//div[@class="accordion__header-text___2o9Im"]/div/h2[1]')
        reviews2.append(review_tag.text)           
                                          
    except NoSuchElementException:
         reviews2.append('-')  
            
     # to scrap star rating:
    try:
        rating_tag=driver.find_element(By.XPATH,'//div[@class="accordion__header-text___2o9Im"]/div[1]/div/span[1]')
        star_rating2.append(rating_tag.text) 
        
    except NoSuchElementException:
         star_rating2.append('-') 
            
    try:
        
        size_tag=driver.find_element(By.XPATH,'//div[@class="accordion__header-text___2o9Im"]/div[1]/div/span[1]')
        size2.append('-')
        
    except NoSuchElementException:
         size2.append('-')  
            
    try:
        
        comfort_tag=driver.find_element(By.XPATH,'//div[@class="accordion__header-text___2o9Im"]/div[1]/div/span[1]')
        comfort2.append('-')
        
    except NoSuchElementException:
        comfort2.append('-')  
        
    try:
       
        quality_tag=driver.find_element(By.XPATH,'//div[@class="accordion__header-text___2o9Im"]/div[1]/div/span[1]')
        quality2.append('-')
        
    except NoSuchElementException:
        quality2.append('-')  
                       
            
print(len(reviews2),len(star_rating2),len(size2),len(comfort2),len(quality2))

48 48 48 48 48

In [231]:
table3_2={"REVIEWS":reviews2,"STAR_RATING":star_rating2,"SIZE":size2,"COMFORT":comfort2,"QUALITY":quality2}
df32=pd.DataFrame(table3_2)
df32

            REVIEWS STAR_RATING SIZE COMFORT QUALITY
0    Reviews (4992)         4.8    -       -       -
1    Reviews (7381)         4.7    -       -       -
2    Reviews (7381)         4.7    -       -       -
3    Reviews (4986)         4.8    -       -       -
4   Reviews (19870)         4.8    -       -       -
5     Reviews (270)         4.4    -       -       -
6     Reviews (860)         4.6    -       -       -
7     Reviews (119)         4.6    -       -       -
8     Reviews (399)         4.4    -       -       -
9     Reviews (396)         4.4    -       -       -
10    Reviews (127)         4.2    -       -       -
11    Reviews (254)         4.2    -       -       -
12    Reviews (161)         4.2    -       -       -
13    Reviews (181)         4.7    -       -       -
14    Reviews (230)         4.4    -       -       -
15    Reviews (260)         4.7    -       -       -
16     Reviews (17)         4.4    -       -       -
17   Reviews (1247)         4.6    -       -       -
18     Reviews (40)         4.1    -       -       -
19     Reviews (50)         4.1    -       -       -
20    Reviews (136)         4.7    -       -       -
21    Reviews (414)         4.6    -       -       -
22    Reviews (270)         4.6    -       -       -
23     Reviews (17)         4.6    -       -       -
24     Reviews (54)         4.3    -       -       -
25     Reviews (98)         4.3    -       -       -
26    Reviews (166)         4.6    -       -       -
27     Reviews (17)         4.6    -       -       -
28     Reviews (79)         4.4    -       -       -
29    Reviews (399)         4.4    -       -       -
30   Reviews (1638)         4.6    -       -       -
31    Reviews (182)         4.5    -       -       -
32    Reviews (216)         4.4    -       -       -
33    Reviews (273)         4.7    -       -       -
34    Reviews (135)         4.4    -       -       -
35    Reviews (628)         4.6    -       -       -
36    Reviews (175)         4.6    -       -       -
37      Reviews (6)         4.8    -       -       -
38    Reviews (399)         4.4    -       -       -
39     Reviews (18)         4.8    -       -       -
40     Reviews (98)         4.3    -       -       -
41   Reviews (1508)         4.7    -       -       -
42   Reviews (2144)         4.7    -       -       -
43                -           -    -       -       -
44      Reviews (5)         3.8    -       -       -
45      Reviews (5)         3.8    -       -       -
46    Reviews (260)         4.7    -       -       -
47     Reviews (58)         4.8    -       -       -

## 3. us.puma.com

In [38]:
driver=webdriver.Chrome()

In [39]:
driver.get('https://us.puma.com/us/en')

In [40]:
search_button=driver.find_element(By.XPATH,'/html/body/div[1]/div[1]/div/nav/div/div/button[2]')

search_button.click()
#time.sleep(5)

In [41]:
search_item=driver.find_element(By.XPATH,'/html/body/div[1]/div[1]/div/nav/div/div/div[1]/div[2]/div[1]/div/form/input')
search_item.send_keys('shoes')

In [42]:
search_item.click()
time.sleep(5)

In [43]:
shoes=driver.find_element(By.XPATH,'/html/body/div[2]/div[1]/div/nav/div/div/div[1]/div[2]/div[2]/div/div/div/div[1]/div/ul/li[3]/a/span')
shoes.click()

In [44]:
# Table.1.3:
shoe_name3=[]
category3=[]
no_of_colors3=[]
price3=[]

In [45]:
for _ in range(0,2):    
    driver.execute_script("window.scrollBy(0,100)")
      
    # to scrap shoe_name
    try:
        name_tag=driver.find_elements(By.XPATH,'//*[@data-test-id="product-list-item"]/a[1]/div[1]/div[3]/h3[1]')
        for i in name_tag:
            shoe_name3.append(i.text.split('\n')[0])
            
    except NoSuchElementException:
         shoe_name3.append('-')             
    
    # to scrap category:
    try:
        category_tag=driver.find_elements(By.XPATH,'//*[@data-test-id="product-list-item"]/a[1]/div[1]/div[3]/h3[1]')
        for i in category_tag:
            
            result=re.search(r"\bWomen\b|\bMen\b|\bkid's\b|\bchild\b",str(i.text))
            if result is None:
                category3.append(None)
                
            else:    
                category3.append(result.group(0))
            
    except NoSuchElementException:
         category3.append('-')             
    
    # to scrap no_of_colors:
    try:
        colors_tag=driver.find_elements(By.XPATH,'//*[@data-test-id="product-list-item"]/a[1]/div[1]/div[2]/span[1]')
        for i in colors_tag:
            no_of_colors3.append(i.text)
    except NoSuchElementException:
         no_of_colors3.append('-')             
        
    # to scrap price
    try:
        price_tag=driver.find_elements(By.XPATH,'//*[@data-test-id="product-list-item"]/a[1]/div[1]/div[3]/div[1]/span[1]')
        for i in price_tag:
            price3.append(i.text)
    except NoSuchElementException:
         price3.append('-')             
            
        
print(len(shoe_name3),len(category3),len(no_of_colors3),len(price3))

48 48 48 48

In [46]:
table1_3={"SHOE_NAME":shoe_name3,"CATEGORY":category3,"NO_OF_COLORS":no_of_colors3,"PRICE":price3}
df3=pd.DataFrame(table1_3)
df3

,SHOE_NAME,CATEGORY,NO_OF_COLORS,PRICE
0,MELO x DEXTER'S LAB MB.03 Men's Basketball Shoes,Men,1 COLOR,$135.00
1,PUMA x LAMELO BALL MB.03 Toxic Men's Basketbal...,Men,1 COLOR,$125.00
2,FENTY x PUMA Creeper Phatty Women's Sneakers,Women,3 COLORS,$140.00
3,PUMA x LAMELO BALL MB.01 Golden Child Men's Ba...,Men,1 COLOR,$140.00
4,PUMA x LAMELO BALL MB.01 Golden Child Big Kids...,None,1 COLOR,$120.00
5,Riaze Prowl Rainbow Women's Sneakers,Women,1 COLOR,$45.99
6,Viz Runner Repeat Men's Running Sneakers,Men,3 COLORS,$42.99
7,FENTY x PUMA Creeper Phatty Women's Sneakers,Women,3 COLORS,$140.00
8,Suede Classic XXI Sneakers,None,9 COLORS,$75.00
9,Ella Lace Up Women's Shoes,Women,2 COLORS,$42.99
10,Tazon Advance Bold Men's Sneakers,Men,2 COLORS,$34.99
11,PUMA x LAMELO BALL MB.03 Chino Hills Men's Bas...,Men,1 COLOR,$125.00
12,Viz Runner Repeat Men's Running Sneakers,Men,3 COLORS,$42.99
13,Softride Sophia 2 Women's Slip-on Shoes,Women,2 COLORS,$34.99
14,Star Vital Women's Training Shoes,Women,2 COLORS,$45.99
15,FENTY x PUMA Creeper Phatty Women's Sneakers,Women,3 COLORS,$140.00
16,Astro Kick Sneakers,None,4 COLORS,$40.99
17,Contempt Demi Men's Training Shoes,Men,2 COLORS,$45.99
18,PUMA x LAMELO BALL MB.03 LaFrancé Men's Basket...,Men,1 COLOR,$125.00
19,Suede Classic XXI Sneakers,None,9 COLORS,$75.00
20,Better Foam Prowl Slip On Women's Training Shoes,Women,1 COLOR,$40.99
21,PUMA Smash 3.0 Menswear Men's Sneakers,Men,1 COLOR,$32.99
22,Tazon 6 FM Men's Sneakers,Men,2 COLORS,$34.99
23,Trinity Men's Sneakers,Men,3 COLORS,$65.99
24,MELO x DEXTER'S LAB MB.03 Men's Basketball Shoes,Men,1 COLOR,$135.00
25,PUMA x LAMELO BALL MB.03 Toxic Men's Basketbal...,Men,1 COLOR,$125.00
26,FENTY x PUMA Creeper Phatty Women's Sneakers,Women,3 COLORS,$140.00
27,PUMA x LAMELO BALL MB.01 Golden Child Men's Ba...,Men,1 COLOR,$140.00
28,PUMA x LAMELO BALL MB.01 Golden Child Big Kids...,None,1 COLOR,$120.00
29,Riaze Prowl Rainbow Women's Sneakers,Women,1 COLOR,$45.99
30,Viz Runner Repeat Men's Running Sneakers,Men,3 COLORS,$42.99
31,FENTY x PUMA Creeper Phatty Women's Sneakers,Women,3 COLORS,$140.00
32,Suede Classic XXI Sneakers,None,9 COLORS,$75.00
33,Ella Lace Up Women's Shoes,Women,2 COLORS,$42.99
34,Tazon Advance Bold Men's Sneakers,Men,2 COLORS,$34.99
35,PUMA x LAMELO BALL MB.03 Chino Hills Men's Bas...,Men,1 COLOR,$125.00
36,Viz Runner Repeat Men's Running Sneakers,Men,3 COLORS,$42.99
37,Softride Sophia 2 Women's Slip-on Shoes,Women,2 COLORS,$34.99
38,Star Vital Women's Training Shoes,Women,2 COLORS,$45.99
39,FENTY x PUMA Creeper Phatty Women's Sneakers,Women,3 COLORS,$140.00
40,Astro Kick Sneakers,None,4 COLORS,$40.99
41,Contempt Demi Men's Training Shoes,Men,2 COLORS,$45.99
42,PUMA x LAMELO BALL MB.03 LaFrancé Men's Basket...,Men,1 COLOR,$125.00
43,Suede Classic XXI Sneakers,None,9 COLORS,$75.00
44,Better Foam Prowl Slip On Women's Training Shoes,Women,1 COLOR,$40.99
45,PUMA Smash 3.0 Menswear Men's Sneakers,Men,1 COLOR,$32.99
46,Tazon 6 FM Men's Sneakers,Men,2 COLORS,$34.99
47,Trinity Men's Sneakers,Men,3 COLORS,$65.99

In [47]:
for _ in range(0,6):    
    driver.execute_script("window.scrollBy(0,1000)")
    
    try:
        shoe_url3=[]
        url_tag=driver.find_elements(By.XPATH,'//*[@data-test-id="product-list-item-link"]')
        for i in url_tag:
            shoe_url3.append(i.get_attribute("href"))
            
    except NoSuchElementException:
         shoe_url.append('-')    
print(len(shoe_url3))

48

In [48]:
shoe_url3

['https://us.puma.com/us/en/pd/melo-x-dexters-lab-mb-03-mens-basketball-shoes/379330?search=true&swatch=01',
 'https://us.puma.com/us/en/pd/puma-x-lamelo-ball-mb-03-toxic-mens-basketball-shoes/378916?search=true&swatch=01',
 'https://us.puma.com/us/en/pd/fenty-x-puma-creeper-phatty-womens-sneakers/399332?search=true&swatch=01',
 'https://us.puma.com/us/en/pd/puma-x-lamelo-ball-mb-01-golden-child-mens-basketball-shoes/379223?search=true&swatch=01',
 'https://us.puma.com/us/en/pd/puma-x-lamelo-ball-mb-01-golden-child-big-kids-basketball-shoes/379297?search=true&swatch=01',
 'https://us.puma.com/us/en/pd/riaze-prowl-rainbow-womens-sneakers/194482?search=true&swatch=01',
 'https://us.puma.com/us/en/pd/viz-runner-repeat-mens-running-sneakers/377333?search=true&swatch=02',
 'https://us.puma.com/us/en/pd/fenty-x-puma-creeper-phatty-womens-sneakers/399332?search=true&swatch=03',
 'https://us.puma.com/us/en/pd/suede-classic-xxi-sneakers/374915?search=true&swatch=01',
 'https://us.puma.com/us/en/pd/ella-lace-up-womens-shoes/193919?search=true&swatch=01',
 'https://us.puma.com/us/en/pd/tazon-advance-bold-mens-sneakers/378245?search=true&swatch=01',
 'https://us.puma.com/us/en/pd/puma-x-lamelo-ball-mb-03-chino-hills-mens-basketball-shoes/379235?search=true&swatch=01',
 'https://us.puma.com/us/en/pd/viz-runner-repeat-mens-running-sneakers/377333?search=true&swatch=01',
 'https://us.puma.com/us/en/pd/softride-sophia-2-womens-slip-on-shoes/378787?search=true&swatch=03',
 'https://us.puma.com/us/en/pd/star-vital-womens-training-shoes/194331?search=true&swatch=19',
 'https://us.puma.com/us/en/pd/fenty-x-puma-creeper-phatty-womens-sneakers/399332?search=true&swatch=02',
 'https://us.puma.com/us/en/pd/astro-kick-sneakers/369115?search=true&swatch=01',
 'https://us.puma.com/us/en/pd/contempt-demi-mens-training-shoes/193160?search=true&swatch=01',
 'https://us.puma.com/us/en/pd/puma-x-lamelo-ball-mb-03-lafranc%C3%A9-mens-basketball-shoes/379233?search=true&swatch=01',
 'https://us.puma.com/us/en/pd/suede-classic-xxi-sneakers/374915?search=true&swatch=12',
 'https://us.puma.com/us/en/pd/better-foam-prowl-slip-on-womens-training-shoes/378754?search=true&swatch=01',
 'https://us.puma.com/us/en/pd/puma-smash-3-0-menswear-mens-sneakers/395630?search=true&swatch=01',
 'https://us.puma.com/us/en/pd/tazon-6-fm-mens-sneakers/189873?search=true&swatch=03',
 'https://us.puma.com/us/en/pd/trinity-mens-sneakers/389289?search=true&swatch=24',
 'https://us.puma.com/us/en/pd/softride-sophia-2-womens-slip-on-shoes/378787?search=true&swatch=01',
 'https://us.puma.com/us/en/pd/starla-fade-womens-training-shoes/378631?search=true&swatch=01',
 'https://us.puma.com/us/en/pd/scoot-zeros-georgia-peach-mens-basketball-shoes/379908?search=true&swatch=07',
 'https://us.puma.com/us/en/pd/puma-x-lamelo-ball-mb-01-lo-mens-basketball-shoes/376941?search=true&swatch=12',
 'https://us.puma.com/us/en/pd/suede-classic-xxi-sneakers/374915?search=true&swatch=04',
 'https://us.puma.com/us/en/pd/f1%C2%AE-austin-grand-prix-speedcat-pro-mens-driving-shoes/308277?search=true&swatch=01',
 'https://us.puma.com/us/en/pd/scuderia-ferrari-x-joshua-vides-speedcat-pro-mens-driving-shoes/307996?search=true&swatch=01',
 'https://us.puma.com/us/en/pd/star-vital-mens-training-shoes/379912?search=true&swatch=01',
 'https://us.puma.com/us/en/pd/puma-serve-pro-mens-sneakers/380188?search=true&swatch=04',
 'https://us.puma.com/us/en/pd/scuderia-ferrari-speedcat-pro-carlos-sainz-puma-75th-year-anniversary-celebration-mens-driving-shoes/308181?search=true&swatch=01',
 'https://us.puma.com/us/en/pd/mercedes-amg-petronas-speedcat-pro-george-russell-puma-75th-year-anniversary-celebration-mens-driving-shoes/308271?search=true&swatch=01',
 'https://us.puma.com/us/en/pd/ferrari-ionf-miami-mens-motorsport-shoes/307506?search=true&swatch=01',
 'https://us.puma.com/us/en/pd/suede-classic-xxi-womens-sneakers/381410?search=true&swatch=85',
 'https://us.puma.com/us/en/pd/smash-3-0-l-mens-sneakers/390987?search=true&swatch=17',
 'https://us.puma.com/us/en/pd/rs-x-camo-dye-mens-sneakers/396075?search=true&swatch=01',
 'https://us.puma.com/us/en/pd/fenty-x-puma-creeper-phatty-mens-sneakers/396403?search=true&swatch=01',
 'https://us.puma.com/us/en/pd/astro-kick-sneakers/369115?search=true&swatch=02',
 'https://us.puma.com/us/en/pd/tazon-6-fm-mens-sneakers/189873?search=true&swatch=02',
 'https://us.puma.com/us/en/pd/softride-enzo-evo-wide-sneakers/377843?search=true&swatch=01',
 'https://us.puma.com/us/en/pd/pacer-future-lux-womens-sneakers/380606?search=true&swatch=01',
 'https://us.puma.com/us/en/pd/puma-hoops-x-gremlins-all-pro-nitro%E2%84%A2-mens-basketball-shoes/379303?search=true&swatch=01',
 'https://us.puma.com/us/en/pd/astro-kick-sneakers/369115?search=true&swatch=07',
 'https://us.puma.com/us/en/pd/future-rider-peb-womens-sneakers/392699?search=true&swatch=01',
 'https://us.puma.com/us/en/pd/fastroid-running-shoes/379068?search=true&swatch=04']

In [49]:
# Table.2.3:
count_of_size3=[]
color1_3=[]
color2_3=[]
color3_3=[]
color4_3=[]
color5_3=[] 
style_code_3=[]

In [50]:
# table.3.2:
reviews3=[]
star_rating3=[]

In [51]:
# scraping table2 data

for url in shoe_url3:
    driver.get(url)
    time.sleep(5)
    
    
    # to scrap count_of_sizes:
    try:
        count_tag=driver.find_element(By.XPATH,'//div[@class="space-y-4 relative"]')
        # Extracting the table data:
        count=0
        #data=[]
        matches=driver.find_elements(By.TAG_NAME,'/div/label')
        for match in matches:
            count=count+1
            #data.append(match.text)
        #for label in count_tag.find_elements(By.TAG_NAME,'//label'):
            #data.append(label.text)
        
        count_of_size3.append(count)
    
    except NoSuchElementException:
        count_of_size3.append('-') 
            
    # to scrap color1:
    try:
        color1_3_tag=driver.find_element(By.XPATH,'//div[@class="tw-xf6gca tw-1p4ksvz"]/h4')
        colors13=color1_3_tag.text.split('-')
        color1_3.append(colors13[0])
            
    except NoSuchElementException:
        color1_3.append('-')         
            
            
     # to scrap color2:
    try:
        color2_3_tag=driver.find_element(By.XPATH,'//div[@class="tw-xf6gca tw-1p4ksvz"]/h4')
        colors23=color2_3_tag.text.split('-')
        if len(colors23)>=2:
            color2_3.append(colors23[1])
        else:
            color2_3.append('-')
    except NoSuchElementException:
         color2_3.append('-')   
            
    # to scrap color3:
    try:
        color3_3_tag=driver.find_element(By.XPATH,'//div[@class="tw-xf6gca tw-1p4ksvz"]/h4')
        colors33=color3_3_tag.text.split('-')
        if len(colors33)>=3:
            color3_3.append(colors33[2])
            
        else:
            color3_3.append('-')  
            
    except NoSuchElementException:
        color3_3.append('-')  
            
    # to scrap color4:
    try:
        color4_3_tag=driver.find_element(By.XPATH,'//div[@class="tw-xf6gca tw-1p4ksvz"]/h4')
        colors43=color4_3_tag.text.split('-')
        if len(colors43)>=4:
            color4_3.append(colors43[3])
        else:
            color4_3.append('-') 
            
    except NoSuchElementException:
        color4_3.append('-')    
            
     # to scrap color4:
    try:
        color5_3_tag=driver.find_element(By.XPATH,'//div[@class="tw-xf6gca tw-1p4ksvz"]/h4')
        colors53=color5_3_tag.text.split('-')
        if len(colors53)>=5:
            color5_3.append(colors53[4])
        else:
            color5_3.append('-')     
            
    except NoSuchElementException:
         color5_3.append('-')     
            
     # to scrap color1:
    try:
        style_tag3=driver.find_element(By.XPATH,'//div[@class="tw-1uc1ku0 tw-1p4ksvz pb-4"]/ul/li[1]')
        style_code_3.append(style_tag3.text)
            
    except NoSuchElementException:
         style_code_3.append('-')         
                   
    try:
        review_tag=driver.find_element(By.XPATH,'//*[@id="product-reviews"]/div/h2[1]')
        reviews3.append(review_tag.text)
        
    except NoSuchElementException:
         reviews3.append('-')  
            
    try:
        rating_tag=driver.find_element(By.XPATH,'//div[@class="flex items-center text-puma-black-500"]/div[1]')
        star_rating3.append(rating_tag.text)
        
    except NoSuchElementException:
        star_rating3.append('-')  
               
            
print(len(count_of_size3),len(color1_3),len(color2_3),len(color3_3),len(color4_3),len(color5_3),len(style_code_3),len(reviews3),len(star_rating3))

48 48 48 48 48 48 48 48 48

In [52]:
table2_3={"COUNT_OF_SIZES":count_of_size3,"COLOR1":color1_3,"COLOR2":color2_3,"COLOR3":color3_3,"COLOR4":color4_3,"COLOR5":color5_3,"STYLE_CODE":style_code_3}
df23=pd.DataFrame(table2_3)
df23

,COUNT_OF_SIZES,COLOR1,COLOR2,COLOR3,COLOR4,COLOR5,STYLE_CODE
0,0,Poison Pink,Fluro Orange Pes,-,-,-,Style: 379330_01
1,0,Purple Glimmer,Green Gecko,-,-,-,Style: 378916_01
2,0,PUMA Black,Warm White,Gum,-,-,Style: 399332_01
3,0,Metallic Gold,Fiery Coral,-,-,-,Style: 379223_01
4,0,Metallic Gold,Fiery Coral,-,-,-,Style: 379297_01
5,0,Puma Black,Luminous Pink,-,-,-,Style: 194482_01
6,0,Puma Black,Puma White,-,-,-,Style: 377333_02
7,0,Lavender Alert,Burnt Red,Gum,-,-,Style: 399332_03
8,0,Puma Black,Puma White,-,-,-,Style: 374915_01
9,0,Puma White,Puma Silver,-,-,-,Style: 193919_01
10,0,PUMA Black,PUMA Black,-,-,-,Style: 378245_01
11,0,Feather Gray,Lime Smash,-,-,-,Style: 379235_01
12,0,Puma White,Puma Black,-,-,-,Style: 377333_01
13,0,Future Pink,Rose Gold,Frosty Pink,-,-,Style: 378787_03
14,0,PUMA Black,PUMA Silver,-,-,-,Style: 194331_19
15,0,Speed Blue,Lime Pow,Gum,-,-,Style: 399332_02
16,0,Puma Black,Puma White,Puma Team Gold,-,-,Style: 369115_01
17,0,Puma Black,Asphalt,-,-,-,Style: 193160_01
18,0,Fluro Green Pes,PUMA Green,Fluro Yellow Pes,-,-,Style: 379233_01
19,0,Puma Black,Puma Black,-,-,-,Style: 374915_12
20,0,PUMA Black,PUMA Gold,Ash Gray,-,-,Style: 378754_01
21,0,Chocolate Chip,Alpine Snow,Hot Heat,-,-,Style: 395630_01
22,0,Puma Black,Puma Silver,-,-,-,Style: 189873_03
23,0,Cool Dark Gray,Gray Fog,Silver Mist,-,-,Style: 389289_24
24,0,PUMA Black,PUMA White,-,-,-,Style: 378787_01
25,0,PUMA White,Rose Dust,-,-,-,Style: 378631_01
26,0,Passionfruit,PUMA Green,Peach Fizz,-,-,Style: 379908_07
27,0,PUMA Black,PUMA Black,-,-,-,Style: 376941_12
28,0,Peacoat,Puma White,-,-,-,Style: 374915_04
29,0,Flat Medium Gray,Pop Red,PUMA Black,-,-,Style: 308277_01
30,0,PUMA White,Rosso Corsa,-,-,-,Style: 307996_01
31,0,PUMA Black,Concrete Gray,-,-,-,Style: 379912_01
32,0,Puma Black,Puma Black,Puma White,Puma Team Gold,-,Style: 380188_04
33,0,Rosso Corsa,PUMA Black,-,-,-,Style: 308181_01
34,0,PUMA Black,PUMA White,-,-,-,Style: 308271_01
35,0,PUMA White,-,-,-,-,Style: 307506_01
36,0,Icy Blue,PUMA White,-,-,-,Style: 381410_85
37,0,PUMA White,Club Red,PUMA Gold,-,-,Style: 390987_17
38,0,Myrtle,Fall Foliage,-,-,-,Style: 396075_01
39,0,PUMA Black,Warm White,Gum,-,-,Style: 396403_01
40,0,Forest Night,Puma White,Puma Team Gold,-,-,Style: 369115_02
41,0,Puma White,Puma Black,Puma Silver,-,-,Style: 189873_02
42,0,Puma Black,CASTLEROCK,-,-,-,Style: 377843_01
43,0,Puma Black,Rose Gold,-,-,-,Style: 380606_01
44,0,PUMA White,-,-,-,-,Style: 379303_01
45,0,Rhubarb,Puma White,Puma Team Gold,-,-,Style: 369115_07
46,0,PUMA White,Frosted Ivory,Puma Team Gold,-,-,Style: 392699_01
47,0,PUMA White,PUMA Silver,Cherry Tomato,-,-,Style: 379068_04

### Table.3

In [56]:
size3=[]
comfort3=[]
quality3=[]

In [57]:

for url in shoe_url3:
    driver.get(url)
    time.sleep(5)
    
    try:
        
        size_tag=driver.find_element(By.XPATH,'//*[@id="product-reviews"]/div/h2[1]')
        size3.append('-')
        
    except NoSuchElementException:
         size3.append('-')  
            
    try:
        
        comfort_tag=driver.find_element(By.XPATH,'//div[@class="flex items-center text-puma-black-500"]/div[1]')
        comfort3.append('-')
        
    except NoSuchElementException:
        comfort3.append('-')  
        
    try:
       
        quality_tag=driver.find_element(By.XPATH,'//*[@id="product-reviews"]/div/h2[1]')
        quality3.append('-')
        
    except NoSuchElementException:
        quality3.append('-')  
                
        
print(len(size3),len(comfort3),len(quality3))

48 48 48

In [58]:
table3_3={"REVIEWS":reviews3,"STAR_RATING":star_rating3,"SIZE":size3,"COMFORT":comfort3,"QUALITY":quality3}
df33=pd.DataFrame(table3_3)
df33

          REVIEWS       STAR_RATING SIZE COMFORT QUALITY
0     Reviews (3)  Average: 5.0 / 5    -       -       -
1    Reviews (80)  Average: 4.2 / 5    -       -       -
2    Reviews (17)  Average: 4.8 / 5    -       -       -
3    Reviews (28)  Average: 4.5 / 5    -       -       -
4    Reviews (11)  Average: 3.7 / 5    -       -       -
5    Reviews (82)  Average: 4.4 / 5    -       -       -
6   Reviews (355)  Average: 4.2 / 5    -       -       -
7    Reviews (17)  Average: 4.8 / 5    -       -       -
8   Reviews (443)  Average: 4.2 / 5    -       -       -
9   Reviews (124)  Average: 4.5 / 5    -       -       -
10   Reviews (99)  Average: 4.3 / 5    -       -       -
11   Reviews (11)  Average: 3.3 / 5    -       -       -
12  Reviews (355)  Average: 4.2 / 5    -       -       -
13   Reviews (18)  Average: 4.4 / 5    -       -       -
14   Reviews (97)  Average: 4.3 / 5    -       -       -
15   Reviews (17)  Average: 4.8 / 5    -       -       -
16  Reviews (158)  Average: 3.7 / 5    -       -       -
17   Reviews (79)  Average: 4.0 / 5    -       -       -
18   Reviews (30)  Average: 4.1 / 5    -       -       -
19  Reviews (443)  Average: 4.2 / 5    -       -       -
20   Reviews (10)  Average: 4.2 / 5    -       -       -
21    Reviews (9)  Average: 3.7 / 5    -       -       -
22  Reviews (182)  Average: 4.5 / 5    -       -       -
23   Reviews (17)  Average: 3.9 / 5    -       -       -
24   Reviews (18)  Average: 4.4 / 5    -       -       -
25    Reviews (4)  Average: 3.3 / 5    -       -       -
26    Reviews (1)                      -       -       -
27   Reviews (39)  Average: 4.1 / 5    -       -       -
28  Reviews (443)  Average: 4.2 / 5    -       -       -
29    Reviews (0)                      -       -       -
30    Reviews (0)                      -       -       -
31    Reviews (7)  Average: 4.6 / 5    -       -       -
32   Reviews (24)  Average: 3.8 / 5    -       -       -
33    Reviews (0)                      -       -       -
34    Reviews (1)                      -       -       -
35    Reviews (1)                      -       -       -
36  Reviews (168)  Average: 4.3 / 5    -       -       -
37    Reviews (7)  Average: 3.6 / 5    -       -       -
38   Reviews (15)  Average: 4.1 / 5    -       -       -
39    Reviews (4)  Average: 5.0 / 5    -       -       -
40  Reviews (158)  Average: 3.7 / 5    -       -       -
41  Reviews (182)  Average: 4.5 / 5    -       -       -
42   Reviews (41)  Average: 4.4 / 5    -       -       -
43   Reviews (27)  Average: 4.0 / 5    -       -       -
44    Reviews (2)                      -       -       -
45  Reviews (158)  Average: 3.7 / 5    -       -       -
46    Reviews (4)  Average: 5.0 / 5    -       -       -
47    Reviews (1)                      -       -       -

# 4. www.skechers.com

In [101]:
driver=webdriver.Chrome()

In [97]:
driver.get('https://www.skechers.com/search/?q=shoe')

In [87]:
# Table.1.4:
shoe_name4=[]
category4=[]
no_of_colors4=[]
price4=[]

In [89]:
for page in range(0,2):
    
    # to scrap shoe_name
    try:
        name_tag=driver.find_elements(By.XPATH,'//a[@class="link c-product-tile__title "]')
        for i in name_tag:
            shoe_name4.append(i.text)
            
    except NoSuchElementException:
         shoe_name4.append('-')  
        
    
    # to scrap category:
    try:
        category_tag=driver.find_elements(By.XPATH,'//div[@class="c-product-tile__gender"]')
        for i in category_tag:
            category4.append(i.text)
    except NoSuchElementException:
         category4.append('-')         
    
    # to scrap no_of_colors:
    try:
        colors_tag=driver.find_elements(By.XPATH,'//div[@class="c-product-tile__color-swatches__label"]')
        for i in colors_tag:
            no_of_colors4.append(i.text)   
            
    except NoSuchElementException:
         no_of_colors4.append('-')         
       
    # to scrap price
    try:
        price_tag=driver.find_elements(By.XPATH,'//div[@class="price"]/span')
        for i in price_tag:
            price4.append(i.text)
            
    except NoSuchElementException:
         price4.append('-')         
            
    
        
    load_more=driver.find_element(By.XPATH,'/html/body/div[2]/div[2]/div/div/div/div[2]/div/div[2]/div[3]/div[28]/div/div/a')
    load_more.click()                                 
    time.sleep(5)    
        
print(len(shoe_name4),len(category4),len(no_of_colors4),len(price4))

72 72 72 72

In [90]:
table1_4={"SHOE_NAME":shoe_name4,"CATEGORY":category4,"NO_OF_COLORS":no_of_colors4,"PRICE":price4}
df4=pd.DataFrame(table1_4)
df4

,SHOE_NAME,CATEGORY,NO_OF_COLORS,PRICE
0,Skechers Slip-ins: Summits - Dazzling Haze,WOMEN'S,3 Colors,$75.00
1,Skechers Slip-ins: Ultra Flex 3.0 - Brilliant,WOMEN'S,4 Colors,$90.00
2,Skechers Slip-ins: GO WALK Flex - Grand Entry,WOMEN'S,5 Colors,$75.00
3,Skechers Slip-ins Work: Summits SR - Enslee,WOMEN'S,1 Color,$75.00
4,Skechers Slip-ins: Ultra Flex 3.0 - Smooth Step,WOMEN'S,4 Colors,$90.00
...,...,...,...,...
67,Skechers Slip-ins: Virtue - Sleek,WOMEN'S,4 Colors,$75.00 - $80.00
68,Max Cushioning Elite 2.0,WOMEN'S,5 Colors,$100.00
69,Ultra Flex - Harmonious,WOMEN'S,2 Colors,$80.00
70,Summits - Bright Charmer,WOMEN'S,1 Color,Price reduced from\n$65.00\nto\n$44.99
71,Skechers Slip-Ins: GO WALK Arch Fit 2.0 - Delara,WOMEN'S,4 Colors,$95.00

### Table.2

In [98]:
for page in range(0,10):
    
    try:
        shoe_url4=[]
        url_tag=driver.find_elements(By.XPATH,'//a[@class="link c-product-tile__title "]')
        for i in url_tag:
            shoe_url4.append(i.get_attribute("href"))
            
    except NoSuchElementException:
        shoe_url4.append('-')     
                   
        
    load_more=driver.find_element(By.XPATH,'/html/body/div[2]/div[2]/div/div/div/div[2]/div/div[2]/div[3]/div[28]/div/div/a')
    load_more.click()                                 
    time.sleep(5)    
print(len(shoe_url4))

24

In [99]:
# Table.2.4:
count_of_size4=[]
color1_4=[]
color2_4=[]
color3_4=[]
color4_4=[]
color5_4=[] 
style_code4=[]

In [102]:
# scraping table2 data

for url in shoe_url4:
    driver.get(url)
    time.sleep(5)
    
    
    # to scrap count_of_sizes:
    try:
        count_tag=driver.find_elements(By.XPATH,'//div[@class="mt2-sm css-12whm6j"]')
        # Extracting the table data:
        #data=[]
        count=0
        matches=driver.find_elements(By.TAG_NAME,'//label')
        for match in matches:
            count=count+1
            #data.append(match.text)
        #for label in count_tag.find_elements(By.TAG_NAME,'//label'):
            #data.append(label.text)
        
        count_of_size4.append(count)
    
    except NoSuchElementException:
         count_of_size4.append('-') 
            
    # to scrap color1:
    try:
        color1_4_tag=driver.find_element(By.XPATH,'')
        color1_4.append(color1_4_tag.text)
            
    except NoSuchElementException:
         color1_3.append('-')         
            
            
     # to scrap color1:
    try:
        color2_4_tag=driver.find_element(By.XPATH,'')
        color2_4.append(color2_4_tag.text)
            
    except NoSuchElementException:
         color2_4.append('-')   
            
    # to scrap color1:
    try:
        color3_4_tag=driver.find_element(By.XPATH,'')
        color3_4.append(color3_4_tag.text)
            
    except NoSuchElementException:
         color3_4.append('-')  
            
    # to scrap color1:
    try:
        color4_4_tag=driver.find_element(By.XPATH,'')
        color4_4.append(color4_4_tag.text)
            
    except NoSuchElementException:
         color4_4.append('-')    
            
     # to scrap color1:
    try:
        color5_4_tag=driver.find_element(By.XPATH,'')
        color5_4.append(color5_4_tag.text)
            
    except NoSuchElementException:
         color5_4.append('-')     
            
     # to scrap color1:
    try:
        style_tag4=driver.find_element(By.XPATH,'')
        style_code4.append(style_tag4.text)
            
    except NoSuchElementException:
         style_code4.append('-')         
                   
                                          

print(len(count_of_size4),len(color1_4),len(color2_4),len(color3_4),len(color4_4),len(color5_4),len(style_code4))

InvalidSelectorException: Message: invalid selector: Unable to locate an element with the xpath expression  because of the following error:
SyntaxError: Failed to execute 'evaluate' on 'Document': The string '' is not a valid XPath expression.
  (Session info: chrome=120.0.6099.129); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#invalid-selector-exception
Stacktrace:
	GetHandleVerifier [0x00007FF60B242142+3514994]
	(No symbol) [0x00007FF60AE60CE2]
	(No symbol) [0x00007FF60AD076AA]
	(No symbol) [0x00007FF60AD0CFC0]
	(No symbol) [0x00007FF60AD0F38F]
	(No symbol) [0x00007FF60AD0F480]
	(No symbol) [0x00007FF60AD51624]
	(No symbol) [0x00007FF60AD5197C]
	(No symbol) [0x00007FF60AD94EE7]
	(No symbol) [0x00007FF60AD7602F]
	(No symbol) [0x00007FF60AD928F6]
	(No symbol) [0x00007FF60AD75D93]
	(No symbol) [0x00007FF60AD44BDC]
	(No symbol) [0x00007FF60AD45C64]
	GetHandleVerifier [0x00007FF60B26E16B+3695259]
	GetHandleVerifier [0x00007FF60B2C6737+4057191]
	GetHandleVerifier [0x00007FF60B2BE4E3+4023827]
	GetHandleVerifier [0x00007FF60AF904F9+689705]
	(No symbol) [0x00007FF60AE6C048]
	(No symbol) [0x00007FF60AE68044]
	(No symbol) [0x00007FF60AE681C9]
	(No symbol) [0x00007FF60AE588C4]
	BaseThreadInitThunk [0x00007FFC5641257D+29]
	RtlUserThreadStart [0x00007FFC580CAA58+40]

In [ ]:
table2_4={"COUNT_OF_SIZES":count_of_sizes4,"COLOR1":color1_4,"COLOR2":color2_4,"COLOR3":color3_4,"COLOR4":color4_4,"COLOR5":color5_4,"STYLE_CODE":style_code4}
df24=pd.DataFrame(table2_4)
df24

#### Access for this Website is Not allowed.. again n again asking to confirm that "u r not a robot".. only 1st page data able to scrap.. Facing problem is scraping the url page data.. still added the code for reference

## 5.www.columbia.com

In [74]:
driver=webdriver.Chrome()

In [75]:
driver.get('https://www.columbia.com/')

In [77]:
search_button=driver.find_element(By.XPATH,'/html/body/header/div/div/div[3]/div[2]/div[1]/input')

search_button.click()
#time.sleep(5)

In [78]:
search_item=driver.find_element(By.XPATH,'/html/body/header/div/div/div[3]/div[2]/div[1]/input')
search_item.send_keys('shoes')

In [79]:
search=driver.find_element(By.XPATH,'/html/body/header/div/div/div[3]/div[2]/div[1]/i')
search.click()

In [80]:
# Table.1.5:
shoe_name5=[]
category5=[]
no_of_colors5=[]
price5=[]

In [81]:
for _ in range(0,2):
    driver.execute_script("window.scrollBy(0,100)")
    # to scrap shoe_url
    try:
        shoe_url5=[]
        url_tag=driver.find_elements(By.XPATH,'//a[@class="single-product"]')
        for i in url_tag:
            shoe_url5.append(i.get_attribute("href"))
            
    except NoSuchElementException:
         shoe_url5.append('-')     
                   
  
    # to scrap shoe_name
    try:
        name_tag=driver.find_elements(By.XPATH,'//div[@class="caption"]/h4[1]/span[1]/a')
        for i in name_tag:
            shoe_name5.append(i.text)
    except NoSuchElementException:
        shoe_name5.append('-')       
    
    # to scrap category:
    
    try:
        category_tag=driver.find_elements(By.XPATH,'//div[@class="caption"]/h4[1]/span[1]/a[1]')
        for i in category_tag:
            result=re.search(r"\bWomen\b|\bMen\b",i.text)
            category5.append(result.group())
            
    except NoSuchElementException:
        category5.append('-')
        
    # to scrap no_of_colors:
    try:
        colors_tag=driver.find_elements(By.XPATH,'//div[@class="caption"]/h4[1]/span[1]')
        for i in colors_tag:
            no_of_colors5.append("1")
        
    except NoSuchElementException:
        no_of_colors5.append('-')   
        
    # to scrap price
    try:
        price_tag=driver.find_elements(By.XPATH,'//div[@class="caption"]/p[1]/span[1]')
        for i in price_tag:
            price5.append(i.text)
            
    except NoSuchElementException:
        price5.append('-')        
        
print(len(shoe_name5),len(category5),len(no_of_colors5),len(price5))

30 30 30 30

In [82]:
len(shoe_url5)

30

## Table.1

In [83]:
table1_5={"SHOE_NAME":shoe_name5,"CATEGORY":category5,"NO_OF_COLORS":no_of_colors5,"PRICE":price5}
df5=pd.DataFrame(table1_5)
df5

,SHOE_NAME,CATEGORY,NO_OF_COLORS,PRICE
0,Columbia Men Black WOODBURN II CHUKKA OMNI-HEA...,Men,1,"9,999"
1,Columbia Men Green EXPEDITIONIST SHIELD Water ...,Men,1,"14,999"
2,Columbia Women White MINX SLIP IV Water Resist...,Women,1,"10,999"
3,Columbia Men Grey CRESTWOOD MID Water Resistan...,Men,1,"9,999"
4,Columbia Men Brown Crestwood Water Resistant S...,Men,1,"8,999"
5,Columbia Women White TRAILSTORM Water Resistan...,Women,1,"8,999"
6,Columbia Women Black TRAILSTORM MID OMNI HEAT ...,Women,1,"12,999"
7,Columbia Men Blue PEAKFREAK X2 OUTDRY (Complet...,Men,1,"10,999"
8,Columbia Women Red PEAKFREAK X2 OUTDRY (Comple...,Women,1,"9,999"
9,Columbia Women Grey TRAILSTORM PEAK MID,Women,1,"10,399"
10,Columbia Women Black TRAILSTORM PEAK MID,Women,1,"10,399"
11,Columbia Women Grey TRAILSTORM Water Resistant...,Women,1,"7,199"
12,Columbia Men Brown CRESTWOOD Water Resistant S...,Men,1,"8,099"
13,Columbia Women Black SH/FT OUTDRY MID (Complet...,Women,1,"9,799"
14,Columbia Men Black TRAILSTORM PEAK MID,Men,1,"10,399"
15,Columbia Men Black WOODBURN II CHUKKA OMNI-HEA...,Men,1,"9,999"
16,Columbia Men Green EXPEDITIONIST SHIELD Water ...,Men,1,"14,999"
17,Columbia Women White MINX SLIP IV Water Resist...,Women,1,"10,999"
18,Columbia Men Grey CRESTWOOD MID Water Resistan...,Men,1,"9,999"
19,Columbia Men Brown Crestwood Water Resistant S...,Men,1,"8,999"
20,Columbia Women White TRAILSTORM Water Resistan...,Women,1,"8,999"
21,Columbia Women Black TRAILSTORM MID OMNI HEAT ...,Women,1,"12,999"
22,Columbia Men Blue PEAKFREAK X2 OUTDRY (Complet...,Men,1,"10,999"
23,Columbia Women Red PEAKFREAK X2 OUTDRY (Comple...,Women,1,"9,999"
24,Columbia Women Grey TRAILSTORM PEAK MID,Women,1,"10,399"
25,Columbia Women Black TRAILSTORM PEAK MID,Women,1,"10,399"
26,Columbia Women Grey TRAILSTORM Water Resistant...,Women,1,"7,199"
27,Columbia Men Brown CRESTWOOD Water Resistant S...,Men,1,"8,099"
28,Columbia Women Black SH/FT OUTDRY MID (Complet...,Women,1,"9,799"
29,Columbia Men Black TRAILSTORM PEAK MID,Men,1,"10,399"

## Table.2

In [84]:
# Table.2.5:
count_of_size5=[]
color1_5=[]
color2_5=[]
color3_5=[]
color4_5=[]
color5_5=[] 
style_code5=[]

In [85]:
# Table.3.5:
reviews5=[]
star_rating5=[]
size5=[]
comfort5=[]
quality5=[]

In [86]:
# scraping table2 data

for url in shoe_url5:
    driver.get(url)
    time.sleep(5)
    
    
    # to scrap count_of_sizes:
    try:
        count_tag=driver.find_elements(By.XPATH,'//div[@class="option-main"][1]')
        # Extracting the table data:
        #data=[]
        count=0
        matches=driver.find_elements(By.TAG_NAME,'/div/label')
        for match in matches:
            count=count+1
            #data.append(match.text)
        #for label in count_tag.find_elements(By.TAG_NAME,'//label'):
            #data.append(label.text)
        
        count_of_size5.append(count)
    
    except NoSuchElementException:
         count_of_size5.append('-') 
            
    # to scrap color1:
    try:
        color1_5_tag=driver.find_element(By.XPATH,'//div[@class="grop-product"]/label')
        colors15=color1_5_tag.text.split(',')
        color1_5.append(colors15[0])
            
    except NoSuchElementException:
         color1_5.append('-')         
            
            
     # to scrap color2:
    try:
        color2_5_tag=driver.find_element(By.XPATH,'//div[@class="grop-product"]/label')
        colors25=color2_5_tag.text.split(',')
        if len(colors25)>=2:
            color2_5.append(colors25[1])
        else:
            color2_5.append('-') 
    except NoSuchElementException:
         color2_5.append('-')   
            
    # to scrap color3:
    try:
        color3_5_tag=driver.find_element(By.XPATH,'//div[@class="grop-product"]/label')
        colors35=color3_5_tag.text.split(',')
        if len(colors35)>=3:
            color3_5.append(colors35[2])
        else:
            color3_5.append('-')
            
    except NoSuchElementException:
         color3_5.append('-')  
            
    # to scrap color4:
    try:
        color4_5_tag=driver.find_element(By.XPATH,'//div[@class="grop-product"]/label')
        colors45=color4_5_tag.text.split(',')
        if len(colors45)>=4:
            color4_5.append()
        else:
            color4_5.append('-')
            
    except NoSuchElementException:
         color4_5.append('-')    
            
     # to scrap color5:
    try:
        color5_5_tag=driver.find_element(By.XPATH,'//div[@class="grop-product"]/label')
        colors55=color5_5_tag.text.split(',')
        if len(colors55)>=5:
            color5_5.append()
        else:
            color5_5.append('-')
            
    except NoSuchElementException:
         color5_5.append('-')     
            
     # to style code:
    try:
        style_tag5=driver.find_element(By.XPATH,'//div[@class="col-sm-5"]/p')
        style_code5.append(style_tag5.text)
            
    except NoSuchElementException:
         style_code5.append('-')         
                   
     # to scrap reviews:
    try:
        review_tag=driver.find_element(By.XPATH,'//div[@class="review-star-block"]/p/span[1]')
        reviews5.append(review_tag.text)
        
    except NoSuchElementException:
        style_code5.append('-') 
        
     # to scrap Star_rating:
    try:
        rating_tag=driver.find_element(By.XPATH,'//div[@class="review-rating-block"]/div/div[1]')
        star_rating5.append(rating_tag.text)
        
    except NoSuchElementException:
        style_code5.append('-') 
        
         
print(len(count_of_size5),len(color1_5),len(color2_5),len(color3_5),len(color4_5),len(color5_5),len(style_code5),len(reviews5),len(star_rating5))

30 30 30 30 30 30 30 30 30

In [87]:
table2_5={"COUNT_OF_SIZES":count_of_size5,"COLOR1":color1_5,"COLOR2":color2_5,"COLOR3":color3_5,"COLOR4":color4_5,"COLOR5":color5_5,"STYLE_CODE":style_code5}
df25=pd.DataFrame(table2_5)
df25

,COUNT_OF_SIZES,COLOR1,COLOR2,COLOR3,COLOR4,COLOR5,STYLE_CODE
0,0,-,-,-,-,-,SKU : BM3926-010
1,0,-,-,-,-,-,SKU : BM3926-010
2,0,-,-,-,-,-,SKU : BM9083-373
3,0,-,-,-,-,-,SKU : BM9083-373
4,0,Sea Salt,Light Cloud,-,-,-,SKU : BL9797-125
5,0,Sea Salt,Light Cloud,-,-,-,SKU : BL9797-125
6,0,Light Cloud,Sea Salt,-,-,-,SKU : BM5371-020
7,0,Light Cloud,Sea Salt,-,-,-,SKU : BM5371-020
8,0,Mud,Squash,-,-,-,SKU : BM5372-255
9,0,Mud,Squash,-,-,-,SKU : BM5372-255
10,0,Light Sand,Sea Wave,-,-,-,SKU : BL0156-193
11,0,Light Sand,Sea Wave,-,-,-,SKU : BL0156-193
12,0,-,-,-,-,-,SKU : BL8089-010
13,0,-,-,-,-,-,SKU : BL8089-010
14,0,Abyss,Fission,-,-,-,SKU : BM0829-439
15,0,Abyss,Fission,-,-,-,SKU : BM0829-439
16,0,Marionberry,Snowcap,-,-,-,SKU : BL0829-616
17,0,Marionberry,Snowcap,-,-,-,SKU : BL0829-616
18,0,Graphite,Icy Morn,-,-,-,SKU : BL5578-053
19,0,Graphite,Icy Morn,-,-,-,SKU : BL5578-053
20,0,Black,Dark Grey,-,-,-,SKU : BL5578-010
21,0,Black,Dark Grey,-,-,-,SKU : BL5578-010
22,0,Graphite,Dolphin,-,-,-,SKU : BL0156-053
23,0,Graphite,Dolphin,-,-,-,SKU : BL0156-053
24,0,Oatmeal,Beach,-,-,-,SKU : BM5372-241
25,0,Oatmeal,Beach,-,-,-,SKU : BM5372-241
26,0,-,-,-,-,-,SKU : BL1020-012
27,0,-,-,-,-,-,SKU : BL1020-012
28,0,Kettle,Black,-,-,-,SKU : BM5578-005
29,0,Kettle,Black,-,-,-,SKU : BM5578-005

## Table.3:

In [88]:
for url in shoe_url5:
    driver.get(url)
    time.sleep(5)
    
    try:
        
        size_tag=driver.find_element(By.XPATH,'//div[@class="review-star-block"]/p/span[1]')
        size5.append('-')
        
    except NoSuchElementException:
         size3.append('-')  
            
    try:
        
        comfort_tag=driver.find_element(By.XPATH,'//div[@class="review-star-block"]/p/span[1]')
        comfort5.append('-')
        
    except NoSuchElementException:
        comfort5.append('-')  
        
    try:
       
        quality_tag=driver.find_element(By.XPATH,'//div[@class="review-star-block"]/p/span[1]')
        quality5.append('-')
        
    except NoSuchElementException:
        quality5.append('-')  
                
        
print(len(size5),len(comfort5),len(quality5))

30 30 30

In [89]:
table3_5={"REVIEWS":reviews5,"STAR_RATING":star_rating5,"SIZE":size5,"COMFORT":comfort5,"QUALITY":quality5}
df35=pd.DataFrame(table3_5)
df35

   REVIEWS STAR_RATING SIZE COMFORT QUALITY
0        0       0of 5    -       -       -
1        0       0of 5    -       -       -
2        0       0of 5    -       -       -
3        0       0of 5    -       -       -
4        0       0of 5    -       -       -
5        0       0of 5    -       -       -
6       60       4of 5    -       -       -
7       60       4of 5    -       -       -
8       47       4of 5    -       -       -
9       47       4of 5    -       -       -
10       1       5of 5    -       -       -
11       1       5of 5    -       -       -
12      44       4of 5    -       -       -
13      44       4of 5    -       -       -
14       0       0of 5    -       -       -
15       0       0of 5    -       -       -
16       0       0of 5    -       -       -
17       0       0of 5    -       -       -
18       0       0of 5    -       -       -
19       0       0of 5    -       -       -
20       0       0of 5    -       -       -
21       0       0of 5    -       -       -
22       0       0of 5    -       -       -
23       0       0of 5    -       -       -
24      91       4of 5    -       -       -
25      91       4of 5    -       -       -
26       0       0of 5    -       -       -
27       0       0of 5    -       -       -
28      32       5of 5    -       -       -
29      32       5of 5    -       -       -

## 6. www.woodlandworldwide.com

In [178]:
driver=webdriver.Chrome()

In [179]:
driver.get('https://www.woodlandworldwide.com/')

In [181]:
sneakers=driver.find_element(By.XPATH,'/html/body/div[1]/div[2]/section[2]/div/div/div[2]/div/div[2]/button')
sneakers.click()
time.sleep(5)

In [ ]:
# Table.1.6:
shoe_name6=[]
category6=[]
no_of_colors6=[]
price6=[]

In [163]:
for _ in range(0,2):
    driver.execute_script("window.scrollBy(0,100)")
    
    # to scrap shoe_name
    try:
        name_tag=driver.find_elements(By.XPATH,'//p[@class="productcardplp_productname__F8lks"]')
        for i in name_tag:
            shoe_name6.append(i.text)
    except NoSuchElementException:
        shoe_name6.append('-')       
    
    # to scrap category:
    
    try:
        category_tag=driver.find_elements(By.XPATH,'//p[@class="productcardplp_productname__F8lks"]')
        for i in category_tag:
            category6.append(i.text.split('\n')[0])
            
    except NoSuchElementException:
        category6.append('-')
        
    # to scrap no_of_colors:
    try:
        colors_tag=driver.find_elements(By.XPATH,'//p[@class="productcardplp_productname__F8lks"]')
        for i in colors_tag:
            no_of_colors6.append("1")
        
    except NoSuchElementException:
        no_of_colors6.append('-')   
        
    # to scrap price
    try:
        price_tag=driver.find_elements(By.XPATH,'//p[@class="productcardplp_productprice__jdlz6"]')
        for i in price_tag:
            price6.append(i.text)
            
    except NoSuchElementException:
        price6.append('-')        
        
print(len(shoe_name6),len(category6),len(no_of_colors6),len(price6))

48 48 48 48

In [169]:
table1_6={"SHOE_NAME":shoe_name6,"CATEGORY":category6,"NO_OF_COLORS":no_of_colors6,"PRICE":price6}
df6=pd.DataFrame(table1_6)
df6

,SHOE_NAME,CATEGORY,NO_OF_COLORS,PRICE
0,Black Slip-on Shoe for Men,Black Slip-on Shoe for Men,1,₹2095₹1414
1,Navy Slip-on Shoe for Men,Navy Slip-on Shoe for Men,1,₹2995₹2021
2,Navy Sports Shoe for Men,Navy Sports Shoe for Men,1,₹2495₹1684
3,White Sneakers for Men,White Sneakers for Men,1,₹2495₹1684
4,Black Sneaker for Men,Black Sneaker for Men,1,₹2495
5,Black/Lgrey Slip Shoe for Men,Black/Lgrey Slip Shoe for Men,1,₹2295₹1445
6,Grey slip-on shoe for men,Grey slip-on shoe for men,1,₹1995₹1346
7,Snaype casual sneaker for men,Snaype casual sneaker for men,1,₹3995₹2157
8,Teal Sneaker for men,Teal Sneaker for men,1,₹2195₹1382
9,Dgrey Slip-on Shoe for Men,Dgrey Slip-on Shoe for Men,1,₹2795₹1886
10,Navy sneakers for Men,Navy sneakers for Men,1,₹2795₹1886
11,Woodland Red sneakers,Woodland Red sneakers,1,₹3695₹1995
12,Grey Slip-on Shoe for Men,Grey Slip-on Shoe for Men,1,₹2495₹1684
13,White/Blue Sports Shoes for Men,White/Blue Sports Shoes for Men,1,₹7495
14,Lgrey/Orange Sports Shoes for Men,Lgrey/Orange Sports Shoes for Men,1,₹7495
15,Black Fabric Luxury Sports Shoes,Black Fabric Luxury Sports Shoes,1,₹7495₹4047
16,Black Sports Shoes for Men,Black Sports Shoes for Men,1,₹7495
17,White/Black Sports Shoe for Men,White/Black Sports Shoe for Men,1,₹7495
18,White Fabric Luxury Sports Shoes,White Fabric Luxury Sports Shoes,1,₹7495₹4047
19,Blue sneakers for men,Blue sneakers for men,1,₹6495₹3507
20,Black/Red Sneaker for Men,Black/Red Sneaker for Men,1,₹2795₹1886
21,Black Slip-on Sneaker,Black Slip-on Sneaker,1,₹5995₹3237
22,Beige Fabric Luxury Sports Shoes,Beige Fabric Luxury Sports Shoes,1,₹7495₹4047
23,RB Brown Sneakers for men,RB Brown Sneakers for men,1,₹6995₹3147
24,Black Slip-on Shoe for Men,Black Slip-on Shoe for Men,1,₹2095₹1414
25,Navy Slip-on Shoe for Men,Navy Slip-on Shoe for Men,1,₹2995₹2021
26,Navy Sports Shoe for Men,Navy Sports Shoe for Men,1,₹2495₹1684
27,White Sneakers for Men,White Sneakers for Men,1,₹2495₹1684
28,Black Sneaker for Men,Black Sneaker for Men,1,₹2495
29,Black/Lgrey Slip Shoe for Men,Black/Lgrey Slip Shoe for Men,1,₹2295₹1445
30,Grey slip-on shoe for men,Grey slip-on shoe for men,1,₹1995₹1346
31,Snaype casual sneaker for men,Snaype casual sneaker for men,1,₹3995₹2157
32,Teal Sneaker for men,Teal Sneaker for men,1,₹2195₹1382
33,Dgrey Slip-on Shoe for Men,Dgrey Slip-on Shoe for Men,1,₹2795₹1886
34,Navy sneakers for Men,Navy sneakers for Men,1,₹2795₹1886
35,Woodland Red sneakers,Woodland Red sneakers,1,₹3695₹1995
36,Grey Slip-on Shoe for Men,Grey Slip-on Shoe for Men,1,₹2495₹1684
37,White/Blue Sports Shoes for Men,White/Blue Sports Shoes for Men,1,₹7495
38,Lgrey/Orange Sports Shoes for Men,Lgrey/Orange Sports Shoes for Men,1,₹7495
39,Black Fabric Luxury Sports Shoes,Black Fabric Luxury Sports Shoes,1,₹7495₹4047
40,Black Sports Shoes for Men,Black Sports Shoes for Men,1,₹7495
41,White/Black Sports Shoe for Men,White/Black Sports Shoe for Men,1,₹7495
42,White Fabric Luxury Sports Shoes,White Fabric Luxury Sports Shoes,1,₹7495₹4047
43,Blue sneakers for men,Blue sneakers for men,1,₹6495₹3507
44,Black/Red Sneaker for Men,Black/Red Sneaker for Men,1,₹2795₹1886
45,Black Slip-on Sneaker,Black Slip-on Sneaker,1,₹5995₹3237
46,Beige Fabric Luxury Sports Shoes,Beige Fabric Luxury Sports Shoes,1,₹7495₹4047
47,RB Brown Sneakers for men,RB Brown Sneakers for men,1,₹6995₹3147

## Table.2

In [186]:
for _ in range(0,2):
    driver.execute_script("window.scrollBy(0,100)")
    
    
     # to scrap shoe_url
    try:
        shoe_url6=[]
        url_tag=driver.find_elements(By.XPATH,'//a[@class="MuiTypography-root MuiTypography-inherit MuiLink-root MuiLink-underlineAlways css-15kjgm"][1]')
        for i in url_tag:
            shoe_url6.append(i.get_attribute("href"))
            
    except NoSuchElementException:
         shoe_url6.append('-')
            
print(len(shoe_url6))

48

In [187]:
shoe_url6

['https://www.woodlandworldwide.com/productinfo/FGC026041122A-BLACK',
 'https://www.woodlandworldwide.com/productinfo/FGC0Y9039132A-NAVY',
 'https://www.woodlandworldwide.com/productinfo/FGC0Z7041612A-NAVY',
 'https://www.woodlandworldwide.com/productinfo/FGC0Z7044742A-WHITE',
 'https://www.woodlandworldwide.com/productinfo/FGC0Z7044752A-BLACK',
 'https://www.woodlandworldwide.com/productinfo/FGC0Y9040822A-BLACK_LGREY',
 'https://www.woodlandworldwide.com/productinfo/FGC0Z7041642A-GREY',
 'https://www.woodlandworldwide.com/productinfo/FGC0L4033001A-SNAYPE',
 'https://www.woodlandworldwide.com/productinfo/FGC026041142A-TEAL',
 'https://www.woodlandworldwide.com/productinfo/FGC0Y9039142A-DGREY',
 'https://www.woodlandworldwide.com/productinfo/FGC0Z7040072A-NAVY',
 'https://www.woodlandworldwide.com/productinfo/FGC0C8012921B-RED',
 'https://www.woodlandworldwide.com/productinfo/FGC0Y9041192A-GREY',
 'https://www.woodlandworldwide.com/productinfo/FGC0DN0AR892A-WHITE_BLUE',
 'https://www.woodlandworldwide.com/productinfo/FGC0DY0AR872A-LGREY_ORANGE',
 'https://www.woodlandworldwide.com/productinfo/FGC0H40S9622A-BLACK',
 'https://www.woodlandworldwide.com/productinfo/FGC0DN0AR922A-BLACK',
 'https://www.woodlandworldwide.com/productinfo/FGC0DN0AR882A-WHITE_BLACK',
 'https://www.woodlandworldwide.com/productinfo/FGC0H40S9632A-WHITE',
 'https://www.woodlandworldwide.com/productinfo/FGC0H40S7552A-BLUE',
 'https://www.woodlandworldwide.com/productinfo/FGC0Y9040932A-BLACK_RED',
 'https://www.woodlandworldwide.com/productinfo/FGC0H40S7562A-BLACK',
 'https://www.woodlandworldwide.com/productinfo/FGC0H40S9642A-BEIGE',
 'https://www.woodlandworldwide.com/productinfo/FGC0Z3024211C-RB_BROWN',
 'https://www.woodlandworldwide.com/productinfo/FGC0DN0AR912A-WHITE',
 'https://www.woodlandworldwide.com/productinfo/FGC0510R2012A-BEIGE',
 'https://www.woodlandworldwide.com/productinfo/FGC0BB033761A-NAVY',
 'https://www.woodlandworldwide.com/productinfo/FGC0510R2022A-WHITE',
 'https://www.woodlandworldwide.com/productinfo/FGC0H40S7542A-BLUE',
 'https://www.woodlandworldwide.com/productinfo/FGC0H40S7572A-BLACK',
 'https://www.woodlandworldwide.com/productinfo/FGC0EM0S0152A-BLACK_LGREY',
 'https://www.woodlandworldwide.com/productinfo/FGC0510R2032A-GREY',
 'https://www.woodlandworldwide.com/productinfo/FGC0H40T3262A-OLIVE',
 'https://www.woodlandworldwide.com/productinfo/FGC0180T8762A-BLACK_GREY',
 'https://www.woodlandworldwide.com/productinfo/FGC0180T8752A-BLUE_WHITE',
 'https://www.woodlandworldwide.com/productinfo/FGC0510R1992A-BLACK',
 'https://www.woodlandworldwide.com/productinfo/FGC0B3025091A-DOVE_WHITE',
 'https://www.woodlandworldwide.com/productinfo/FGC051028671A-DGREY',
 'https://www.woodlandworldwide.com/productinfo/FGC0510S0112A-NAVY',
 'https://www.woodlandworldwide.com/productinfo/FGC0DY0S0072A-SAND',
 'https://www.woodlandworldwide.com/productinfo/FGC0V2025091A-NAVY',
 'https://www.woodlandworldwide.com/productinfo/FGC0180V3512A-BLUE',
 'https://www.woodlandworldwide.com/productinfo/FGC0H40U8442A-GREY',
 'https://www.woodlandworldwide.com/productinfo/FGC0510R2062A-LGREY',
 'https://www.woodlandworldwide.com/productinfo/FGC0G2030171A-CAMEL',
 'https://www.woodlandworldwide.com/productinfo/FGC028030281A-DGREEN',
 'https://www.woodlandworldwide.com/productinfo/FGC0150S0032A-ARMY',
 'https://www.woodlandworldwide.com/productinfo/FGC0H40U8012A-WHITE']

In [188]:
# Table.2.6:
count_of_size6=[]
color1_6=[]
color2_6=[]
color3_6=[]
color4_6=[]
color5_6=[] 
style_code6=[]

In [189]:
# Table .3.3:
reviews6=[]
star_rating6=[]

In [193]:
size6=[]
comfort6=[]
quality6=[]

In [190]:
# scraping table2 data

for url in shoe_url6:
    driver.get(url)
    time.sleep(5)
    
    
    # to scrap count_of_sizes:
    try:
        count_tag=driver.find_elements(By.XPATH,'//div[@class="MuiBox-root css-acwcvw"]')
        # Extracting the table data:
        #data=[]
        count=0
        matches=driver.find_elements(By.TAG_NAME,'/div/div')
        for match in matches:
            count=count+1
            #data.append(match.text)
        #for label in count_tag.find_elements(By.TAG_NAME,'//label'):
            #data.append(label.text)
        
        count_of_size6.append(count)
    
    except NoSuchElementException:
         count_of_size6.append('-') 
            
    # to scrap color1:
    try:
        color1_6_tag=driver.find_element(By.XPATH,'//div[@class="MuiBox-root css-0"]/div/div/h5[1]')
        colors16=color1_6_tag.text.split('" "')
        color1_6.append(colors16[0])
            
    except NoSuchElementException:
        color1_6.append('-')         
            
            
     # to scrap color2:
    try:
        color2_6_tag=driver.find_element(By.XPATH,'//div[@class="MuiBox-root css-0"]/div/div/h5[1]')
        colors26=color2_6_tag.text.split('" "') 
        if len(colors26)>=2:
                        color2_6.append(colors26[1])
        else:
            color2_6.append('-')
                        
    except NoSuchElementException:
         color2_6.append('-')   
            
    # to scrap color3:
    try:
        color3_6_tag=driver.find_element(By.XPATH,'//div[@class="MuiBox-root css-0"]/div/div/h5[1]')
        colors36=color3_6_tag.text.split('" "')
        if len(colors36)>=3:
                        color3_6.append(colors36[2])
                        
        else:
             color3_6.append('-') 
                        
    except NoSuchElementException:
         color3_6.append('-')  
            
    # to scrap color4:
    try:
        color4_6_tag=driver.find_element(By.XPATH,'//div[@class="MuiBox-root css-0"]/div/div/h5[1]')
        colors46= color4_6_tag.text.split('" "') 
        if len(colors46)>=4:
                        color4_6.append(colors46[3])
        else:
            color4_6.append('-')            
                        
    except NoSuchElementException:
         color4_6.append('-')    
            
     # to scrap color5:
    try:
        color5_6_tag=driver.find_element(By.XPATH,'//div[@class="MuiBox-root css-0"]/div/div/h5[1]')
        colors56= color5_6_tag.text.split('" "') 
        if len(colors56)>=5:
                        color5_6.append(colors56[4])
                        
        else:
            color5_6.append('-')
                        
    except NoSuchElementException:
         color5_6.append('-')     
            
     # to scrap color1:
    try:
        style_tag6=driver.find_element(By.XPATH,'//div[@class="MuiGrid-root MuiGrid-item MuiGrid-grid-xs-12 MuiGrid-grid-md-5 css-1r482s6"][1]')
        style_code6.append('-')
            
    except NoSuchElementException:
         style_code6.append('-')         
                   
    try:
        #review_tag=driver.find_element(By.XPATH,'')
        reviews6.append('-')
                                                          # reviews and star_rating not mentioned in the web page
    except NoSuchElementException:
        reviews6.append('-')      
        
    try:
        #rating_tag=driver.find_element('By.XPATH,'')
        star_rating6.append('-') 
                                       
    except NoSuchElementException:
        star_rating6.append('-')      
                                          
                                       
        
print(len(count_of_size6),len(color1_6),len(color2_6),len(color3_6),len(color4_6),len(color5_6),len(style_code6),len(reviews6),len(star_rating6))

48 48 48 48 48 48 48 48 48

In [191]:
table2_6={"COUNT_OF_SIZES":count_of_size6,"COLOR1":color1_6,"COLOR2":color2_6,"COLOR3":color3_6,"COLOR4":color4_6,"COLOR5":color5_6,"STYLE_CODE":style_code6}
df26=pd.DataFrame(table2_6)
df26

    COUNT_OF_SIZES        COLOR1 COLOR2 COLOR3 COLOR4 COLOR5 STYLE_CODE
0                0         BLACK      -      -      -      -          -
1                0          NAVY      -      -      -      -          -
2                0          NAVY      -      -      -      -          -
3                0         WHITE      -      -      -      -          -
4                0         BLACK      -      -      -      -          -
5                0   BLACK/LGREY      -      -      -      -          -
6                0          GREY      -      -      -      -          -
7                0        SNAYPE      -      -      -      -          -
8                0          TEAL      -      -      -      -          -
9                0         DGREY      -      -      -      -          -
10               0          NAVY      -      -      -      -          -
11               0           RED      -      -      -      -          -
12               0          GREY      -      -      -      -          -
13               0    WHITE/BLUE      -      -      -      -          -
14               0  LGREY/ORANGE      -      -      -      -          -
15               0         BLACK      -      -      -      -          -
16               0         BLACK      -      -      -      -          -
17               0   WHITE/BLACK      -      -      -      -          -
18               0         WHITE      -      -      -      -          -
19               0          BLUE      -      -      -      -          -
20               0     BLACK/RED      -      -      -      -          -
21               0         BLACK      -      -      -      -          -
22               0         BEIGE      -      -      -      -          -
23               0      RB BROWN      -      -      -      -          -
24               0         WHITE      -      -      -      -          -
25               0         BEIGE      -      -      -      -          -
26               0          NAVY      -      -      -      -          -
27               0         WHITE      -      -      -      -          -
28               0          BLUE      -      -      -      -          -
29               0         BLACK      -      -      -      -          -
30               0   BLACK/LGREY      -      -      -      -          -
31               0          GREY      -      -      -      -          -
32               0         OLIVE      -      -      -      -          -
33               0    BLACK/GREY      -      -      -      -          -
34               0    BLUE/WHITE      -      -      -      -          -
35               0         BLACK      -      -      -      -          -
36               0    DOVE WHITE      -      -      -      -          -
37               0         DGREY      -      -      -      -          -
38               0          NAVY      -      -      -      -          -
39               0          SAND      -      -      -      -          -
40               0          NAVY      -      -      -      -          -
41               0          BLUE      -      -      -      -          -
42               0          GREY      -      -      -      -          -
43               0         LGREY      -      -      -      -          -
44               0         CAMEL      -      -      -      -          -
45               0        DGREEN      -      -      -      -          -
46               0          ARMY      -      -      -      -          -
47               0         WHITE      -      -      -      -          -

## Table.3:

In [194]:
for url in shoe_url6:
    driver.get(url)
    time.sleep(5)
    
    try:
        
        #size_tag=driver.find_element(By.XPATH,'')
        size6.append('-')
        
    except NoSuchElementException:
         size6.append('-')  
            
    try:
        
        #comfort_tag=driver.find_element(By.XPATH,'')
        comfort6.append('-')
        
    except NoSuchElementException:
        comfort6.append('-')  
        
    try:
       
        #quality_tag=driver.find_element(By.XPATH,'')                 ### reviews not given in webpage
        quality6.append('-')
        
    except NoSuchElementException:
        quality6.append('-')  
                
        
print(len(size6),len(comfort6),len(quality6))

48 48 48

In [195]:
table3_6={"REVIEWS":reviews6,"STAR_RATING":star_rating6,"size":size6,"COMFORT":comfort6,"QUALITY":quality6}
df36=pd.DataFrame(table3_6)
df36

   REVIEWS STAR_RATING size COMFORT QUALITY
0        -           -    -       -       -
1        -           -    -       -       -
2        -           -    -       -       -
3        -           -    -       -       -
4        -           -    -       -       -
5        -           -    -       -       -
6        -           -    -       -       -
7        -           -    -       -       -
8        -           -    -       -       -
9        -           -    -       -       -
10       -           -    -       -       -
11       -           -    -       -       -
12       -           -    -       -       -
13       -           -    -       -       -
14       -           -    -       -       -
15       -           -    -       -       -
16       -           -    -       -       -
17       -           -    -       -       -
18       -           -    -       -       -
19       -           -    -       -       -
20       -           -    -       -       -
21       -           -    -       -       -
22       -           -    -       -       -
23       -           -    -       -       -
24       -           -    -       -       -
25       -           -    -       -       -
26       -           -    -       -       -
27       -           -    -       -       -
28       -           -    -       -       -
29       -           -    -       -       -
30       -           -    -       -       -
31       -           -    -       -       -
32       -           -    -       -       -
33       -           -    -       -       -
34       -           -    -       -       -
35       -           -    -       -       -
36       -           -    -       -       -
37       -           -    -       -       -
38       -           -    -       -       -
39       -           -    -       -       -
40       -           -    -       -       -
41       -           -    -       -       -
42       -           -    -       -       -
43       -           -    -       -       -
44       -           -    -       -       -
45       -           -    -       -       -
46       -           -    -       -       -
47       -           -    -       -       -

In [235]:
TABLE1_Final=pd.concat([df1,df2,df3,df5,df6],axis=0)
TABLE1_Final

,SHOE_NAME,CATEGORY,NO_OF_COLORS,PRICE
0,Nike Killshot 2 Leather,Men,5 Colours,MRP : ₹ 7 995.00
1,Nike Air Max SC,Women,4 Colours,MRP : ₹ 5 995.00
2,Nike Air Force 1 '07 LV8,Men,1 Colour,MRP : ₹ 10 795.00
3,Nike Court Vision Low,None,1 Colour,MRP : ₹ 4 995.00
4,Nike Air Force 1 '07 NN,Women,2 Colours,MRP : ₹ 9 695.00
...,...,...,...,...
43,Blue sneakers for men,Blue sneakers for men,1,₹6495₹3507
44,Black/Red Sneaker for Men,Black/Red Sneaker for Men,1,₹2795₹1886
45,Black Slip-on Sneaker,Black Slip-on Sneaker,1,₹5995₹3237
46,Beige Fabric Luxury Sports Shoes,Beige Fabric Luxury Sports Shoes,1,₹7495₹4047
47,RB Brown Sneakers for men,RB Brown Sneakers for men,1,₹6995₹3147

In [236]:
TABLE2_Final=pd.concat([df21,df22,df23,df25,df26],axis=0)
TABLE2_Final

,COUNT_OF_SIZES,COLOR1,COLOR2,COLOR3,COLOR4,COLOR5,STYLE_CODE
0,0,Sail,Gum Yellow,Lucid Green,-,-,Style: 432997-111
1,0,White,Sea Glass,Black,Chlorophyll,-,Style: CW4554-117
2,0,Dark Stucco,Neutral Olive,Phantom,Medium Olive,-,Style: FJ4170-002
3,0,White,University Red,-,-,-,Style: CD5463-102
4,0,Platinum Violet,Coconut Milk,Volt,Sail,-,Style: DV3808-001
...,...,...,...,...,...,...,...
43,0,LGREY,-,-,-,-,-
44,0,CAMEL,-,-,-,-,-
45,0,DGREEN,-,-,-,-,-
46,0,ARMY,-,-,-,-,-
47,0,WHITE,-,-,-,-,-

In [237]:
TABLE3_Final=pd.concat([df31,df32,df33,df35,df36],axis=0)
TABLE3_Final

          REVIEWS STAR_RATING SIZE COMFORT QUALITY size
0    Reviews (72)                -       -       -  NaN
1   Reviews (129)                -       -       -  NaN
2     Reviews (0)                -       -       -  NaN
3   Reviews (186)                -       -       -  NaN
4    Reviews (12)                -       -       -  NaN
..            ...         ...  ...     ...     ...  ...
43              -           -  NaN       -       -    -
44              -           -  NaN       -       -    -
45              -           -  NaN       -       -    -
46              -           -  NaN       -       -    -
47              -           -  NaN       -       -    -

[198 rows x 6 columns]

# Saving into csv file all the 3 tables

In [238]:
TABLE1_Final.to_csv('TABLE1.csv',index=False)

In [239]:
TABLE2_Final.to_csv('TABLE2.csv',index=False)

In [240]:
TABLE3_Final.to_csv('TABLE3.CSV',index=False)

### cross varifying:

In [241]:
T1=pd.read_csv('TABLE1.csv')
T1

,SHOE_NAME,CATEGORY,NO_OF_COLORS,PRICE
0,Nike Killshot 2 Leather,Men,5 Colours,MRP : ₹ 7 995.00
1,Nike Air Max SC,Women,4 Colours,MRP : ₹ 5 995.00
2,Nike Air Force 1 '07 LV8,Men,1 Colour,MRP : ₹ 10 795.00
3,Nike Court Vision Low,NaN,1 Colour,MRP : ₹ 4 995.00
4,Nike Air Force 1 '07 NN,Women,2 Colours,MRP : ₹ 9 695.00
...,...,...,...,...
193,Blue sneakers for men,Blue sneakers for men,1,₹6495₹3507
194,Black/Red Sneaker for Men,Black/Red Sneaker for Men,1,₹2795₹1886
195,Black Slip-on Sneaker,Black Slip-on Sneaker,1,₹5995₹3237
196,Beige Fabric Luxury Sports Shoes,Beige Fabric Luxury Sports Shoes,1,₹7495₹4047
197,RB Brown Sneakers for men,RB Brown Sneakers for men,1,₹6995₹3147

In [242]:
T2=pd.read_csv('TABLE2.csv')
T2

,COUNT_OF_SIZES,COLOR1,COLOR2,COLOR3,COLOR4,COLOR5,STYLE_CODE
0,0,Sail,Gum Yellow,Lucid Green,-,-,Style: 432997-111
1,0,White,Sea Glass,Black,Chlorophyll,-,Style: CW4554-117
2,0,Dark Stucco,Neutral Olive,Phantom,Medium Olive,-,Style: FJ4170-002
3,0,White,University Red,-,-,-,Style: CD5463-102
4,0,Platinum Violet,Coconut Milk,Volt,Sail,-,Style: DV3808-001
...,...,...,...,...,...,...,...
193,0,LGREY,-,-,-,-,-
194,0,CAMEL,-,-,-,-,-
195,0,DGREEN,-,-,-,-,-
196,0,ARMY,-,-,-,-,-
197,0,WHITE,-,-,-,-,-

In [243]:
T3=pd.read_csv('TABLE3.csv')
T3

           REVIEWS STAR_RATING SIZE COMFORT QUALITY size
0     Reviews (72)         NaN    -       -       -  NaN
1    Reviews (129)         NaN    -       -       -  NaN
2      Reviews (0)         NaN    -       -       -  NaN
3    Reviews (186)         NaN    -       -       -  NaN
4     Reviews (12)         NaN    -       -       -  NaN
..             ...         ...  ...     ...     ...  ...
193              -           -  NaN       -       -    -
194              -           -  NaN       -       -    -
195              -           -  NaN       -       -    -
196              -           -  NaN       -       -    -
197              -           -  NaN       -       -    -

[198 rows x 6 columns]